gMoveDescription_Pound::
	.string "A physical attack\ndelivered with a\nlong tail or a\nforeleg, etc.$"

gMoveDescription_KarateChop:: @ 8482874
	.string "The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_DoubleSlap:: @ 84828BD
	.string "The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times.$"

gMoveDescription_CometPunch:: @ 84828FF
	.string "The foe is hit with\na flurry of punches\nthat strike two to\nfive times.$"

gMoveDescription_MegaPunch:: @ 8482946
	.string "The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.$"

gMoveDescription_PayDay:: @ 8482985
	.string "Numerous coins are\nhurled at the foe.\nMoney is earned\nafter battle.$"

gMoveDescription_FirePunch:: @ 84829C9
	.string "The foe is punched\nwith a fiery fist.\nIt may leave the\nfoe with a burn.$"

gMoveDescription_IcePunch:: @ 8482A11
	.string "The foe is punched\nwith an icy fist.\nIt may leave the\nfoe frozen.$"

gMoveDescription_ThunderPunch:: @ 8482A53
	.string "The foe is punched\nwith an electrified\nfist. It may leave\nthe foe paralyzed.$"

gMoveDescription_Scratch:: @ 8482AA0
	.string "Hard, pointed, and\nsharp claws rake\nthe foe.$"

gMoveDescription_ViceGrip:: @ 8482ACD
	.string "Huge, impressive\npincers grip and\nsqueeze the foe.$"

gMoveDescription_Guillotine:: @ 8482B00
	.string "A vicious tearing\nattack with pincers.\nThe foe will faint\nif it hits.$"

gMoveDescription_RazorWind:: @ 8482B46
	.string "Blades of wind hit\nthe foe on the 2nd\nturn. It has a high\ncritical-hit ratio.$"

gMoveDescription_SwordsDance:: @ 8482B94
	.string "A frenetic dance of\nfighting. It sharply\nraises the ATTACK\nstat.$"

gMoveDescription_Cut:: @ 8482BD5
	.string "A basic attack.\nIt can be used to\ncut down thin trees\nand grass.$"

gMoveDescription_Gust:: @ 8482C16
	.string "Strikes the foe\nwith a gust of wind\nwhipped up by\nwings.$"

gMoveDescription_WingAttack:: @ 8482C4F
	.string "The foe is struck\nwith large, imposing\nwings spread wide.$"

gMoveDescription_Whirlwind:: @ 8482C89
	.string "The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.$"

gMoveDescription_Fly:: @ 8482CD3
	.string "A 2-turn move that\nhits on the 2nd\nturn. Use it to fly\nto any known town.$"

gMoveDescription_Bind:: @ 8482D1D
	.string "A long body or\ntentacles are used\nto bind the foe for\ntwo to five turns.$"

gMoveDescription_Slam:: @ 8482D66
	.string "The foe is struck\nwith a long tail,\nvines, etc.$"

gMoveDescription_VineWhip:: @ 8482D96
	.string "The foe is struck\nwith slender, whip-\nlike vines.$"

gMoveDescription_Stomp:: @ 8482DC8
	.string "The foe is stomped\nwith a big foot.\nIt may make the\nfoe flinch.$"

gMoveDescription_DoubleKick:: @ 8482E08
	.string "Two legs are used\nto quickly kick the\nfoe twice in one\nturn.$"

gMoveDescription_MegaKick:: @ 8482E45
	.string "The foe is attacked\nby a kick fired\nwith muscle-packed\npower.$"

gMoveDescription_JumpKick:: @ 8482E83
	.string "The user jumps up\nhigh, then kicks.\nIf it misses, the\nuser hurts itself.$"

gMoveDescription_RollingKick:: @ 8482ECC
	.string "A quick kick from a\nrolling spin.\nIt may make the\nfoe flinch.$"

gMoveDescription_SandAttack:: @ 8482F0A
	.string "A lot of sand is\nhurled in the foe's\nface, reducing its\naccuracy.$"

gMoveDescription_Headbutt:: @ 8482F4C
	.string "The user sticks its\nhead out and rams.\nIt may make the\nfoe flinch.$"

gMoveDescription_HornAttack:: @ 8482F8F
	.string "The foe is jabbed\nwith a sharply\npointed horn to\ninflict damage.$"

gMoveDescription_FuryAttack:: @ 8482FD0
	.string "The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times.$"

gMoveDescription_HornDrill:: @ 8483014
	.string "The horn is rotated\nlike a drill to ram.\nThe foe will faint\nif it hits.$"

gMoveDescription_Tackle:: @ 848305C
	.string "A physical attack\nin which the user\ncharges, full body,\ninto the foe.$"

gMoveDescription_BodySlam:: @ 84830A2
	.string "The user drops its\nfull body on the\nfoe. It may leave\nthe foe paralyzed.$"

gMoveDescription_Wrap:: @ 84830EB
	.string "A long body or\nvines are used to\nwrap the foe for\ntwo to five turns.$"

gMoveDescription_TakeDown:: @ 8483130
	.string "A reckless, full-\nbody charge attack\nthat also hurts the\nuser a little.$"

gMoveDescription_Thrash:: @ 8483178
	.string "The user rampages\nabout for two to\nthree turns, then\nbecomes confused.$"

gMoveDescription_DoubleEdge:: @ 84831BF
	.string "A reckless, life-\nrisking tackle that\nalso hurts the user\na little.$"

gMoveDescription_TailWhip:: @ 8483203
	.string "The user wags its\ntail cutely, making\nthe foe lower its\nDEFENSE stat.$"

gMoveDescription_PoisonSting:: @ 8483249
	.string "The foe is stabbed\nwith a toxic barb,\netc. It may poison\nthe foe.$"

gMoveDescription_Twineedle:: @ 848328B
	.string "The foe is stabbed\ntwice with foreleg\nstingers. It may\npoison the foe.$"

gMoveDescription_PinMissile:: @ 84832D2
	.string "Sharp pins are shot\nat the foe and hit\ntwo to five times\nat once.$"

gMoveDescription_Leer:: @ 8483314
	.string "The foe is given an\nintimidating look\nthat lowers its\nDEFENSE stat.$"

gMoveDescription_Bite:: @ 8483358
	.string "The user bites with\nvicious fangs.\nIt may make the\nfoe flinch.$"

gMoveDescription_Growl:: @ 8483397
	.string "The user growls in\na cute way, making\nthe foe lower its\nATTACK stat.$"

gMoveDescription_Roar:: @ 84833DC
	.string "The foe is made to\nswitch out with an\nally. In the wild,\nthe battle ends.$"

gMoveDescription_Sing:: @ 8483426
	.string "A soothing song\nin a calming voice\nlulls the foe into\na deep slumber.$"

gMoveDescription_Supersonic:: @ 848346C
	.string "The user generates\nodd sound waves.\nIt may confuse the\nfoe.$"

gMoveDescription_SonicBoom:: @ 84834A8
	.string "The foe is hit with\na shock wave that\nalways inflicts 20-\nHP damage.$"

gMoveDescription_Disable:: @ 84834ED
	.string "For a few turns,\nit prevents the foe\nfrom using the move\nit last used.$"

gMoveDescription_Acid:: @ 8483534
	.string "The foe is sprayed\nwith a harsh, hide-\nmelting acid that\nmay lower DEFENSE.$"

gMoveDescription_Ember:: @ 8483580
	.string "The foe is attacked\nwith small flames.\nThe foe may suffer\na burn.$"

gMoveDescription_Flamethrower:: @ 84835C2
	.string "The foe is scorched\nwith intense flames.\nThe foe may suffer\na burn.$"

gMoveDescription_Mist:: @ 8483606
	.string "The ally party is\nprotected by a\nmist that prevents\nstat reductions.$"

gMoveDescription_WaterGun:: @ 848364B
	.string "The foe is struck\nwith a lot of water\nexpelled forcibly\nfrom the mouth.$"

gMoveDescription_HydroPump:: @ 8483693
	.string "A high volume of\nwater is blasted at\nthe foe under great\npressure.$"

gMoveDescription_Surf:: @ 84836D6
	.string "A big wave crashes\ndown on the foe.\nCan also be used\nfor crossing water.$"

gMoveDescription_IceBeam:: @ 848371F
	.string "The foe is struck\nwith an icy beam.\nIt may freeze the\nfoe solid.$"

gMoveDescription_Blizzard:: @ 8483760
	.string "The foe is blasted\nwith a blizzard.\nIt may freeze the\nfoe solid.$"

gMoveDescription_Psybeam:: @ 84837A1
	.string "A peculiar ray is\nshot at the foe.\nIt may leave the\nfoe confused.$"

gMoveDescription_BubbleBeam:: @ 84837E3
	.string "A spray of bubbles\nstrikes the foe.\nIt may lower the\nfoe's SPEED stat.$"

gMoveDescription_AuroraBeam:: @ 848382A
	.string "A rainbow-colored\nattack beam.\nIt may lower the\nfoe's ATTACK stat.$"

gMoveDescription_HyperBeam:: @ 848386D
	.string "A severely damaging\nattack that makes\nthe user rest on\nthe next turn.$"

gMoveDescription_Peck:: @ 84838B3
	.string "The foe is jabbed\nwith a sharply\npointed beak or\nhorn.$"

gMoveDescription_DrillPeck:: @ 84838EA
	.string "A corkscrewing\nattack with the\nsharp beak acting\nas a drill.$"

gMoveDescription_Submission:: @ 8483927
	.string "A reckless, full-\nbody throw attack\nthat also hurts the\nuser a little.$"

gMoveDescription_LowKick:: @ 848396E
	.string "A low, tripping kick\nthat inflicts more\ndamage on heavier\nfoes.$"

gMoveDescription_Counter:: @ 84839AE
	.string "A retaliation move\nthat counters any\nphysical hit with\ndouble the damage.$"

gMoveDescription_SeismicToss:: @ 84839F8
	.string "A gravity-fed throw\nthat causes damage\nmatching the user's\nlevel.$"

gMoveDescription_Strength:: @ 8483A3A
	.string "The foe is slugged\nat maximum power.\nCan also be used\nto move boulders.$"

gMoveDescription_Absorb:: @ 8483A82
	.string "An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_MegaDrain:: @ 8483AC5
	.string "A tough attack that\ndrains half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_LeechSeed:: @ 8483B0C
	.string "A seed is planted\non the foe to steal\nsome HP for the \nuser on every turn.$"

gMoveDescription_Growth:: @ 8483B57
	.string "The user's body is\nforced to grow,\nraising the SP.\nATK stat.$"

gMoveDescription_RazorLeaf:: @ 8483B94
	.string "The foe is hit with\na cutting leaf.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_SolarBeam:: @ 8483BDA
	.string "A 2-turn move that\nblasts the foe with\nabsorbed energy in\nthe 2nd turn.$"

gMoveDescription_PoisonPowder:: @ 8483C22
	.string "A cloud of toxic\ndust is scattered.\nIt may poison the\nfoe.$"

gMoveDescription_StunSpore:: @ 8483C5D
	.string "Paralyzing dust is\nscattered wildly.\nIt may paralyze\nthe foe.$"

gMoveDescription_SleepPowder:: @ 8483C9B
	.string "A sleep-inducing\ndust is scattered\nin high volume\naround a foe.$"

gMoveDescription_PetalDance:: @ 8483CDB
	.string "The user attacks\nwith petals for two\nto three turns,\nthen gets confused.$"

gMoveDescription_StringShot:: @ 8483D24
	.string "The foe is bound\nwith strings shot\nfrom the mouth to\nreduce its SPEED.$"

gMoveDescription_DragonRage:: @ 8483D6B
	.string "The foe is hit with\na shock wave that\nalways inflicts 40-\nHP damage.$"

gMoveDescription_FireSpin:: @ 8483DB0
	.string "The foe is trapped\nin an intense spiral\nof fire that rages\ntwo to five turns.$"

gMoveDescription_ThunderShock:: @ 8483DFE
	.string "An electric shock\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_Thunderbolt:: @ 8483E3E
	.string "A strong electrical\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_ThunderWave:: @ 8483E80
	.string "A weak electric\nshock that is sure\nto cause paralysis\nif it hits.$"

gMoveDescription_Thunder:: @ 8483EC2
	.string "A brutal lightning\nattack that may\nalso leave the foe\nparalyzed.$"

gMoveDescription_RockThrow:: @ 8483F03
	.string "The foe is attacked\nwith a shower of\nsmall, easily\nthrown rocks.$"

gMoveDescription_Earthquake:: @ 8483F44
	.string "An earthquake that\nstrikes all POKéMON\nin battle excluding\nthe user.$"

gMoveDescription_Fissure:: @ 8483F89
	.string "The foe is dropped\ninto a fissure.\nThe foe faints if it\nhits.$"

gMoveDescription_Dig:: @ 8483FC7
	.string "An attack that hits\non the 2nd turn.\nCan also be used\nto exit dungeons.$"

gMoveDescription_Toxic:: @ 848400F
	.string "A move that badly\npoisons the foe.\nIts poison damage\nworsens every turn.$"

gMoveDescription_Confusion:: @ 8484058
	.string "A weak telekinetic\nattack that may\nalso leave the foe\nconfused.$"

gMoveDescription_Psychic:: @ 8484098
	.string "A strong telekinetic\nattack. It may also\nlower the foe's\nSP. DEF stat.$"

gMoveDescription_Hypnosis:: @ 84840DF
	.string "Hypnotic suggestion\nis used to make the\nfoe fall into a\ndeep sleep.$"

gMoveDescription_Meditate:: @ 8484123
	.string "The user meditates\nto awaken its power\nand raise its\nATTACK stat.$"

gMoveDescription_Agility:: @ 8484165
	.string "The user relaxes\nand lightens its\nbody to sharply\nboost its SPEED.$"

gMoveDescription_QuickAttack:: @ 84841A8
	.string "An almost invisibly\nfast attack that\nis certain to strike\nfirst.$"

gMoveDescription_Rage:: @ 84841E9
	.string "An attack that\nbecomes stronger\neach time the user\nis hit in battle.$"

gMoveDescription_Teleport:: @ 848422E
	.string "Use it to flee from\nany wild POKéMON.\nAlso warps to the\nlast POKé CENTER.$"

gMoveDescription_NightShade:: @ 8484278
	.string "An attack with a\nmirage that inflicts\ndamage matching\nthe user's level.$"

gMoveDescription_Mimic:: @ 84842C0
	.string "The user copies the\nmove last used by\nthe foe for the\nrest of the battle.$"

gMoveDescription_Screech:: @ 848430A
	.string "An ear-splitting\nscreech is emitted\nto sharply reduce\nthe foe's DEFENSE.$"

gMoveDescription_DoubleTeam:: @ 8484353
	.string "The user creates\nillusory copies of\nitself to raise its\nevasiveness.$"

gMoveDescription_Recover:: @ 8484398
	.string "A self-healing move\nthat restores HP by\nup to half of the\nuser's maximum HP.$"

gMoveDescription_Harden:: @ 84843E5
	.string "The user stiffens\nall the muscles in\nits body to raise\nits DEFENSE stat.$"

gMoveDescription_Minimize:: @ 848442E
	.string "The user compresses\nall the cells in its\nbody to raise its\nevasiveness.$"

gMoveDescription_Smokescreen:: @ 8484476
	.string "An obscuring cloud\nof smoke or ink\nreduces the foe's\naccuracy.$"

gMoveDescription_ConfuseRay:: @ 84844B5
	.string "The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.$"

gMoveDescription_Withdraw:: @ 84844F3
	.string "The user withdraws\nits body in its hard\nshell, raising its\nDEFENSE stat.$"

gMoveDescription_DefenseCurl:: @ 848453C
	.string "The user curls up\nto conceal weak\nspots and raise its\nDEFENSE stat.$"

gMoveDescription_Barrier:: @ 8484580
	.string "The user creates a\nsturdy wall that\nsharply raises its\nDEFENSE stat.$"

gMoveDescription_LightScreen:: @ 84845C5
	.string "A wall of light\ncuts damage from\nSP. ATK attacks\nfor five turns.$"

gMoveDescription_Haze:: @ 8484606
	.string "Eliminates all stat\nchanges among all\nPOKéMON engaged in\nbattle.$"

gMoveDescription_Reflect:: @ 8484647
	.string "A wall of light\ncuts damage from\nphysical attacks\nfor five turns.$"

gMoveDescription_FocusEnergy:: @ 8484689
	.string "The user takes a\ndeep breath and\nfocuses to raise its\ncritical-hit ratio.$"

gMoveDescription_Bide:: @ 84846D3
	.string "The user endures\nattacks for two\nturns, then strikes\nback double.$"

gMoveDescription_Metronome:: @ 8484715
	.string "Waggles a finger\nand stimulates the\nbrain into using any\nmove at random.$"

gMoveDescription_MirrorMove:: @ 848475E
	.string "The user counters\nthe move last used\nby the foe with the\nsame move.$"

gMoveDescription_SelfDestruct:: @ 84847A2
	.string "The user blows up\nto inflict severe\ndamage, even\nmaking itself faint.$"

gMoveDescription_EggBomb:: @ 84847E8
	.string "A large egg is\nhurled with great\nforce at the foe to\ninflict damage.$"

gMoveDescription_Lick:: @ 848482D
	.string "The foe is licked\nand hit with a long\ntongue. It may\nalso paralyze.$"

gMoveDescription_Smog:: @ 8484871
	.string "The foe is attacked\nwith exhaust gases.\nIt may also poison\nthe foe.$"

gMoveDescription_Sludge:: @ 84848B5
	.string "Toxic sludge is\nhurled at the foe.\nIt may poison the\ntarget.$"

gMoveDescription_BoneClub:: @ 84848F2
	.string "The foe is clubbed\nwith a bone held in\nhand. It may make\nthe foe flinch.$"

gMoveDescription_FireBlast:: @ 848493B
	.string "The foe is hit with\nan intense flame.\nIt may leave the\ntarget with a burn.$"

gMoveDescription_Waterfall:: @ 8484986
	.string "A powerful charge\nattack. It can also\nbe used to climb\na waterfall.$"

gMoveDescription_Clamp:: @ 84849CA
	.string "The foe is clamped\nand squeezed by\nthe user's shell for\ntwo to five turns.$"

gMoveDescription_Swift:: @ 8484A15
	.string "Star-shaped rays\nthat never miss are\nfired at all foes in\nbattle.$"

gMoveDescription_SkullBash:: @ 8484A57
	.string "The user raises its\nDEFENSE in the 1st\nturn, then attacks\nin the 2nd turn.$"

gMoveDescription_SpikeCannon:: @ 8484AA2
	.string "Sharp spikes are\nfired at the foe to\nstrike two to five\ntimes.$"

gMoveDescription_Constrict:: @ 8484AE1
	.string "The foe is attacked\nwith long tentacles\nor vines. It may\nlower SPEED.$"

gMoveDescription_Amnesia:: @ 8484B27
	.string "Forgets about\nsomething and\nsharply raises\nSP. DEF.$"

gMoveDescription_Kinesis:: @ 8484B5B
	.string "The user distracts\nthe foe by bending\na spoon. It may\nlower accuracy.$"

gMoveDescription_SoftBoiled:: @ 8484BA1
	.string "Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.$"

gMoveDescription_HiJumpKick:: @ 8484BEB
	.string "A strong jumping\nknee kick. If it\nmisses, the user is\nhurt.$"

gMoveDescription_Glare:: @ 8484C27
	.string "The user intimidates\nthe foe with the\ndesign on its belly\nto cause paralysis.$"

gMoveDescription_DreamEater:: @ 8484C75
	.string "Absorbs half the\ndamage it inflicted\non a sleeping foe\nto restore HP.$"

gMoveDescription_PoisonGas:: @ 8484CBB
	.string "The foe is sprayed\nwith a cloud of\ntoxic gas that may\npoison the foe.$"

gMoveDescription_Barrage:: @ 8484D01
	.string "Round objects are\nhurled at the foe\nto strike two to\nfive times.$"

gMoveDescription_LeechLife:: @ 8484D42
	.string "An attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_LovelyKiss:: @ 8484D85
	.string "The user forces a\nkiss on the foe\nwith a scary face\nthat induces sleep.$"

gMoveDescription_SkyAttack:: @ 8484DCD
	.string "A 2nd-turn attack\nmove with a high\ncritical-hit ratio.\nThe foe may flinch.$"

gMoveDescription_Transform:: @ 8484E18
	.string "The user transforms\ninto a copy of the\nfoe with even the\nsame move set.$"

gMoveDescription_Bubble:: @ 8484E60
	.string "A spray of bubbles\nhits the foe.\nIt may lower the\nfoe's SPEED stat.$"

gMoveDescription_DizzyPunch:: @ 8484EA4
	.string "The foe is hit with\na rhythmic punch\nthat may leave it\nconfused.$"

gMoveDescription_Spore:: @ 8484EE5
	.string "The user scatters\nbursts of fine\nspores that induce\nsleep.$"

gMoveDescription_Flash:: @ 8484F20
	.string "A blast of light\nthat cuts the foe's\naccuracy. It also\nilluminates caves.$"

gMoveDescription_Psywave:: @ 8484F6A
	.string "The foe is attacked\nwith an odd, hot\nenergy wave that\nvaries in intensity.$"

gMoveDescription_Splash:: @ 8484FB5
	.string "The user just flops\nand splashes around\nwithout having any\neffect.$"

gMoveDescription_AcidArmor:: @ 8484FF8
	.string "The user alters its\ncells to liquefy\nitself and sharply\nraise DEFENSE.$"

gMoveDescription_Crabhammer:: @ 848503F
	.string "A large pincer is\nused to hammer the\nfoe. It has a high\ncritical-hit ratio.$"

gMoveDescription_Explosion:: @ 848508B
	.string "The user explodes\nto inflict terrible\ndamage even while\nfainting itself.$"

gMoveDescription_FurySwipes:: @ 84850D4
	.string "The foe is raked\nwith sharp claws or\nscythes two to five\ntimes.$"

gMoveDescription_Bonemerang:: @ 8485114
	.string "The user throws a\nbone that hits the\nfoe once, then once\nagain on return.$"

gMoveDescription_Rest:: @ 848515E
	.string "The user sleeps for\ntwo turns to fully\nrestore HP and heal\nany status problem.$"

gMoveDescription_RockSlide:: @ 84851AD
	.string "Large boulders are\nhurled at the foe.\nIt may make the\nfoe flinch.$"

gMoveDescription_HyperFang:: @ 84851EF
	.string "The foe is attacked\nwith sharp fangs.\nIt may make the\nfoe flinch.$"

gMoveDescription_Sharpen:: @ 8485231
	.string "The user reduces\nits polygon count\nto sharpen edges\nand raise ATTACK.$"

gMoveDescription_Conversion:: @ 8485277
	.string "The user changes\nits type to match\nthe type of one of\nits moves.$"

gMoveDescription_TriAttack:: @ 84852B8
	.string "A simultaneous\n3-beam attack that\nmay paralyze, burn,\nor freeze the foe.$"

gMoveDescription_SuperFang:: @ 8485301
	.string "The user attacks\nwith sharp fangs\nand halves the\nfoe's HP.$"

gMoveDescription_Slash:: @ 848533C
	.string "The foe is slashed\nwith claws, etc.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Substitute:: @ 8485382
	.string "The user creates a\ndecoy using one-\nquarter of its full\nHP.$"

gMoveDescription_Struggle:: @ 84853BE
	.string "An attack that is\nused only if there\nis no PP. It also\nhurts the user.$"

gMoveDescription_Sketch:: @ 8485405
	.string "This move copies\nthe move last used\nby the foe, then\ndisappears.$"

gMoveDescription_TripleKick:: @ 8485446
	.string "A 3-kick attack\nthat becomes more\npowerful with each\nsuccessive hit.$"

gMoveDescription_Thief:: @ 848548B
	.string "An attack that may\ntake the foe's held\nitem if the user\nisn't holding one.$"

gMoveDescription_SpiderWeb:: @ 84854D6
	.string "Ensnares the foe \nwith sticky string\nso it doesn't flee\nor switch out.$"

gMoveDescription_MindReader:: @ 848551D
	.string "The user predicts\nthe foe's action to\nensure its next\nattack hits.$"

gMoveDescription_Nightmare:: @ 8485560
	.string "A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.$"

gMoveDescription_FlameWheel:: @ 84855AA
	.string "The user makes a\nfiery charge at the\nfoe. It may cause\na burn.$"

gMoveDescription_Snore:: @ 84855E9
	.string "An attack that can\nbe used only while\nasleep. It may\ncause flinching.$"

gMoveDescription_Curse:: @ 848562F
	.string "A move that works\ndifferently for the\nGHOST-type and all\nthe other types.$"

gMoveDescription_Flail:: @ 8485679
	.string "A desperate attack\nthat becomes more\npowerful the less\nHP the user has.$"

gMoveDescription_Conversion2:: @ 84856C1
	.string "The user changes\ntype to make itself\nresistant to the\nlast attack it took.$"

gMoveDescription_Aeroblast:: @ 848570C
	.string "A vortex of air is\nshot at the foe.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_CottonSpore:: @ 8485752
	.string "Cotton-like spores\ncling to the foe,\nsharply reducing\nits SPEED stat.$"

gMoveDescription_Reversal:: @ 8485798
	.string "An all-out attack\nthat becomes more\npowerful the less\nHP the user has.$"

gMoveDescription_Spite:: @ 84857DF
	.string "A move that cuts\n2 to 5 PP from the\nmove last used by\nthe foe.$"

gMoveDescription_PowderSnow:: @ 848581E
	.string "Blasts the foe with\na snowy gust.\nIt may cause\nfreezing.$"

gMoveDescription_Protect:: @ 8485857
	.string "Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.$"

gMoveDescription_MachPunch:: @ 84858A1
	.string "A punch thrown at\nblinding speed.\nIt is certain to\nstrike first.$"

gMoveDescription_ScaryFace:: @ 84858E2
	.string "Frightens the foe\nwith a scary face\nto sharply reduce\nits SPEED.$"

gMoveDescription_FaintAttack:: @ 8485923
	.string "The user draws up\nclose to the foe\ndisarmingly, then\nhits without fail.$"

gMoveDescription_SweetKiss:: @ 848596B
	.string "The user kisses\nthe foe with sweet\ncuteness that\ncauses confusion.$"

gMoveDescription_BellyDrum:: @ 84859AE
	.string "The user maximizes\nits ATTACK stat at\nthe cost of half\nits full HP.$"

gMoveDescription_SludgeBomb:: @ 84859F2
	.string "Filthy sludge is\nhurled at the foe.\nIt may poison the\ntarget.$"

gMoveDescription_MudSlap:: @ 8485A30
	.string "Mud is hurled in\nthe foe's face to\ninflict damage and\nlower its accuracy.$"

gMoveDescription_Octazooka:: @ 8485A7A
	.string "Ink is blasted in\nthe foe's face or\neyes to damage and\nlower accuracy.$"

gMoveDescription_Spikes:: @ 8485AC1
	.string "A trap of spikes is\nlaid around the\nfoe's party to hurt\nfoes switching in.$"

gMoveDescription_ZapCannon:: @ 8485B0C
	.string "An electric blast is\nfired like a cannon\nto inflict damage\nand paralyze.$"

gMoveDescription_Foresight:: @ 8485B55
	.string "Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.$"

gMoveDescription_DestinyBond:: @ 8485B9C
	.string "If the user faints,\nthe foe delivering\nthe final hit also\nfaints.$"

gMoveDescription_PerishSong:: @ 8485BDE
	.string "Any battler that\nhears this faints\nin three turns\nunless it switches.$"

gMoveDescription_IcyWind:: @ 8485C24
	.string "A chilling wind is\nused to attack.\nIt also lowers the\nSPEED stat.$"

gMoveDescription_Detect:: @ 8485C66
	.string "Enables the user to\nevade all attacks.\nIt may fail if used\nin succession.$"

gMoveDescription_BoneRush:: @ 8485CB0
	.string "The user strikes\nthe foe with a bone\nin hand two to five\ntimes.$"

gMoveDescription_LockOn:: @ 8485CF0
	.string "The user locks on\nto the foe, making\nthe next move sure\nto hit.$"

gMoveDescription_Outrage:: @ 8485D30
	.string "The user thrashes\nabout for two to\nthree turns, then\nbecomes confused.$"

gMoveDescription_Sandstorm:: @ 8485D77
	.string "A 5-turn sandstorm\nthat damages all\ntypes except ROCK,\nGROUND, and STEEL.$"

gMoveDescription_GigaDrain:: @ 8485DC1
	.string "A harsh attack that\nabsorbs half the\ndamage it inflicted\nto restore HP.$"

gMoveDescription_Endure:: @ 8485E09
	.string "The user endures\nany hit with 1 HP\nleft. It may fail if\nused in succession.$"

gMoveDescription_Charm:: @ 8485E55
	.string "The foe is charmed\nby the user's cute\nappeals, sharply\ncutting its ATTACK.$"

gMoveDescription_Rollout:: @ 8485EA0
	.string "A 5-turn rolling\nattack that becomes\nstronger each time\nit hits.$"

gMoveDescription_FalseSwipe:: @ 8485EE1
	.string "A restrained attack\nthat always leaves\nthe foe with at\nleast 1 HP.$"

gMoveDescription_Swagger:: @ 8485F24
	.string "A move that makes\nthe foe confused,\nbut also sharply\nraises its ATTACK.$"

gMoveDescription_MilkDrink:: @ 8485F6C
	.string "Heals the user by\nup to half its full\nHP. It can be used\nto heal an ally.$"

gMoveDescription_Spark:: @ 8485FB6
	.string "An electrically\ncharged tackle that\nmay also paralyze\nthe foe.$"

gMoveDescription_FuryCutter:: @ 8485FF5
	.string "An attack that\ngrows stronger on\neach successive\nhit.$"

gMoveDescription_SteelWing:: @ 848602B
	.string "The foe is hit with\nwings of steel.\nIt may also raise\nthe user's DEFENSE.$"

gMoveDescription_MeanLook:: @ 8486075
	.string "The foe is fixed\nwith a mean look\nthat prevents it\nfrom escaping.$"

gMoveDescription_Attract:: @ 84860B7
	.string "If it is the other\ngender, the foe is\nmade infatuated and\nunlikely to attack.$"

gMoveDescription_SleepTalk:: @ 8486105
	.string "While asleep, the\nuser randomly uses\none of the moves it\nknows.$"

gMoveDescription_HealBell:: @ 8486145
	.string "A soothing bell\nchimes to heal the\nstatus problems of\nall allies.$"

gMoveDescription_Return:: @ 8486187
	.string "This attack move\ngrows more powerful\nthe more the user\nlikes its TRAINER.$"

gMoveDescription_Present:: @ 84861D1
	.string "The foe is given a\nbooby-trapped gift.\nIt restores HP\nsometimes, however.$"

gMoveDescription_Frustration:: @ 848621B
	.string "This attack move\ngrows more powerful\nthe less the user\nlikes its TRAINER.$"

gMoveDescription_Safeguard:: @ 8486265
	.string "It protects the\nuser's party from\nall status problems\nfor five turns.$"

gMoveDescription_PainSplit:: @ 84862AB
	.string "The user adds its\nHP to the foe's HP,\nthen equally shares\nthe total HP.$"

gMoveDescription_SacredFire:: @ 84862F3
	.string "A mystical and\npowerful fire\nattack that may\ninflict a burn.$"

gMoveDescription_Magnitude:: @ 8486330
	.string "A ground-shaking\nattack against all\nstanding POKéMON.\nIts power varies.$"

gMoveDescription_DynamicPunch:: @ 8486378
	.string "The foe is punched\nwith the user's full\npower. It confuses\nthe foe if it hits.$"

gMoveDescription_Megahorn:: @ 84863C7
	.string "A brutal ramming\nattack delivered\nwith a tough and\nimpressive horn.$"

gMoveDescription_DragonBreath:: @ 848640B
	.string "The foe is hit with\nan incredible blast\nof breath that may\nalso paralyze.$"

gMoveDescription_BatonPass:: @ 8486455
	.string "The user switches\nout, passing along\nany stat changes\nto the new battler.$"

gMoveDescription_Encore:: @ 848649F
	.string "Makes the foe use\nthe move it last\nused repeatedly for\ntwo to six turns.$"

gMoveDescription_Pursuit:: @ 84864E8
	.string "An attack move that\nworks especially\nwell on a foe that\nis switching out.$"

gMoveDescription_RapidSpin:: @ 8486532
	.string "An attack that\nfrees the user from\nBIND, WRAP, LEECH\nSEED, and SPIKES.$"

gMoveDescription_SweetScent:: @ 8486579
	.string "Allures the foe to\nreduce evasiveness.\nIt also attracts\nwild POKéMON.$"

gMoveDescription_IronTail:: @ 84865BF
	.string "An attack with a\nsteel-hard tail.\nIt may lower the\nfoe's DEFENSE stat.$"

gMoveDescription_MetalClaw:: @ 8486606
	.string "The foe is attacked\nwith steel claws.\nIt may also raise\nthe user's ATTACK.$"

gMoveDescription_VitalThrow:: @ 8486651
	.string "Makes the user\nattack after the\nfoe. In return,\nit will not miss.$"

gMoveDescription_MorningSun:: @ 8486693
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_Synthesis:: @ 84866DE
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_Moonlight:: @ 8486729
	.string "Restores the user's\nHP. The amount of\nHP regained varies\nwith the weather.$"

gMoveDescription_HiddenPower:: @ 8486774
	.string "An attack that\nvaries in type and\nintensity depending\non the user.$"

gMoveDescription_CrossChop:: @ 84867B7
	.string "The foe is hit with\ndouble chops.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Twister:: @ 84867FB
	.string "A vicious twister\nattacks the foe.\nIt may make the\nfoe flinch.$"

gMoveDescription_RainDance:: @ 848683A
	.string "A heavy rain falls\nfor five turns,\npowering up WATER-\ntype moves.$"

gMoveDescription_SunnyDay:: @ 848687C
	.string "The sun blazes for\nfive turns, powering\nup FIRE-type\nmoves.$"

gMoveDescription_Crunch:: @ 84868B8
	.string "The foe is crunched\nwith sharp fangs.\nIt may lower the\nfoe's SP. DEF.$"

gMoveDescription_MirrorCoat:: @ 84868FE
	.string "A retaliation move\nthat pays back the\nfoe's special attack\ndouble.$"

gMoveDescription_PsychUp:: @ 8486941
	.string "The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.$"

gMoveDescription_ExtremeSpeed:: @ 848698A
	.string "A blindingly speedy\ncharge attack that\nalways goes before\nany other.$"

gMoveDescription_AncientPower:: @ 84869CF
	.string "An ancient power is\nused to attack. It\nmay also raise all\nthe user's stats.$"

gMoveDescription_ShadowBall:: @ 8486A1B
	.string "A shadowy blob is\nhurled at the foe.\nMay also lower the\nfoe's SP. DEF.$"

gMoveDescription_FutureSight:: @ 8486A62
	.string "Two turns after\nthis move is used,\nthe foe is attacked\npsychically.$"

gMoveDescription_RockSmash:: @ 8486AA6
	.string "An attack that may\nalso cut DEFENSE.\nIt can also smash\ncracked boulders.$"

gMoveDescription_Whirlpool:: @ 8486AEF
	.string "The foe is trapped\nin a fast, vicious\nwhirlpool for two\nto five turns.$"

gMoveDescription_BeatUp:: @ 8486B36
	.string "All party POKéMON\njoin in the attack.\nThe more allies,\nthe more damage.$"

gMoveDescription_FakeOut:: @ 8486B7E
	.string "An attack that hits\nfirst and causes\nflinching. Usable\nonly on 1st turn.$"

gMoveDescription_Uproar:: @ 8486BC7
	.string "The user attacks in\nan uproar that\nprevents sleep for\ntwo to five turns.$"

gMoveDescription_Stockpile:: @ 8486C10
	.string "The user charges\nup power for use\nlater. It can be\nused three times.$"

gMoveDescription_SpitUp:: @ 8486C55
	.string "The power built\nusing STOCKPILE is\nreleased at once\nfor attack.$"

gMoveDescription_Swallow:: @ 8486C95
	.string "The energy it built\nusing STOCKPILE is\nabsorbed to restore\nHP.$"

gMoveDescription_HeatWave:: @ 8486CD4
	.string "The user exhales a\nheated breath to\nattack. It may also\ninflict a burn.$"

gMoveDescription_Hail:: @ 8486D1C
	.string "A hailstorm lasting\nfive turns damages\nall POKéMON except\nthe ICE-type.$"

gMoveDescription_Torment:: @ 8486D64
	.string "It enrages the foe,\nmaking it incapable\nof using the same\nmove successively.$"

gMoveDescription_Flatter:: @ 8486DB1
	.string "Flattery is used to\nconfuse the foe,\nbut its SP. ATK\nalso rises.$"

gMoveDescription_WillOWisp:: @ 8486DF2
	.string "A sinister, bluish\nwhite flame is shot\nat the foe to\ninflict a burn.$"

gMoveDescription_Memento:: @ 8486E37
	.string "The user faints,\nbut sharply lowers\nthe foe's ATTACK\nand SP. ATK.$"

gMoveDescription_Facade:: @ 8486E79
	.string "An attack that is\nboosted if user is\nburned, poisoned,\nor paralyzed.$"

gMoveDescription_FocusPunch:: @ 8486EBE
	.string "An attack that is\nexecuted last.\nThe user flinches\nif hit beforehand.$"

gMoveDescription_SmellingSalt:: @ 8486F04
	.string "Doubly effective on\na paralyzed foe,\nbut it also cures\nthe foe's paralysis.$"

gMoveDescription_FollowMe:: @ 8486F50
	.string "The user draws\nattention to itself,\nmaking foes attack\nonly the user.$"

gMoveDescription_NaturePower:: @ 8486F96
	.string "An attack that\nchanges type\ndepending on the\nuser's location.$"

gMoveDescription_Charge:: @ 8486FD4
	.string "The user charges\npower to boost the\nELECTRIC move it\nuses next.$"

gMoveDescription_Taunt:: @ 8487014
	.string "The foe is taunted\ninto a rage that\nallows it to use\nonly attack moves.$"

gMoveDescription_HelpingHand:: @ 848705C
	.string "A move that boosts\nthe power of the\nally's attack in a\nbattle.$"

gMoveDescription_Trick:: @ 848709B
	.string "A move that tricks\nthe foe into\ntrading held items\nwith the user.$"

gMoveDescription_RolePlay:: @ 84870DD
	.string "The user mimics the\nfoe completely and\ncopies the foe's\nability.$"

gMoveDescription_Wish:: @ 848711E
	.string "A self-healing move\nthat restores half\nthe full HP on the\nnext turn.$"

gMoveDescription_Assist:: @ 8487163
	.string "The user randomly\npicks and uses a\nmove of an allied\nPOKéMON.$"

gMoveDescription_Ingrain:: @ 84871A1
	.string "The user lays roots\nthat restore HP on\nevery turn.\nIt can't switch out.$"

gMoveDescription_Superpower:: @ 84871E9
	.string "A powerful attack,\nbut it also lowers\nthe user's ATTACK\nand DEFENSE stats.$"

gMoveDescription_MagicCoat:: @ 8487234
	.string "Reflects back the\nfoe's LEECH SEED\nand any status-\ndamaging move.$"

gMoveDescription_Recycle:: @ 8487276
	.string "A move that\nrecycles a used\nitem for use once\nmore.$"

gMoveDescription_Revenge:: @ 84872AA
	.string "An attack move that\ngains in intensity if\nthe target has hurt\nthe user.$"

gMoveDescription_BrickBreak:: @ 84872F2
	.string "An attack that also\nbreaks any barrier\nlike LIGHT SCREEN\nand REFLECT.$"

gMoveDescription_Yawn:: @ 8487338
	.string "A huge yawn lulls\nthe foe into falling\nasleep on the next\nturn.$"

gMoveDescription_KnockOff:: @ 8487378
	.string "Knocks down the\nfoe's held item to\nprevent its use\nduring the battle.$"

gMoveDescription_Endeavor:: @ 84873BE
	.string "Gains power the\nfewer HP the user\nhas compared with\nthe foe.$"

gMoveDescription_Eruption:: @ 84873FB
	.string "The higher the\nuser's HP, the more\npowerful this\nattack becomes.$"

gMoveDescription_SkillSwap:: @ 848743C
	.string "The user employs\nits psychic power\nto swap abilities\nwith the foe.$"

gMoveDescription_Imprison:: @ 848747F
	.string "Prevents foes from\nusing any move\nthat is also known\nby the user.$"

gMoveDescription_Refresh:: @ 84874C1
	.string "A self-healing move\nthat cures the user\nof a poisoning,\nburn, or paralysis.$"

gMoveDescription_Grudge:: @ 848750D
	.string "If the user faints,\nthis move deletes\nthe PP of the move\nthat finished it.$"

gMoveDescription_Snatch:: @ 8487558
	.string "Steals the effects\nof the foe's\nhealing or status-\nchanging move.$"

gMoveDescription_SecretPower:: @ 848759A
	.string "An attack that may\nhave an additional\neffect that varies\nwith the terrain.$"

gMoveDescription_Dive:: @ 84875E5
	.string "The user dives\nunderwater on the\nfirst turn and\nstrikes next turn.$"

gMoveDescription_ArmThrust:: @ 8487628
	.string "A quick flurry of\nstraight-arm\npunches that hit\ntwo to five times.$"

gMoveDescription_Camouflage:: @ 848766B
	.string "Alters the user's\ntype depending on\nthe location's\nterrain.$"

gMoveDescription_TailGlow:: @ 84876A7
	.string "The user flashes a\nlight that sharply\nraises its SP. ATK\nstat.$"

gMoveDescription_LusterPurge:: @ 84876E6
	.string "A burst of light\ninjures the foe. It\nmay also lower the\nfoe's SP. DEF.$"

gMoveDescription_MistBall:: @ 848772D
	.string "A flurry of down\nhits the foe. It\nmay also lower the\nfoe's SP. ATK.$"

gMoveDescription_FeatherDance:: @ 8487771
	.string "The foe is covered\nwith a mass of down\nthat sharply cuts\nthe ATTACK stat.$"

gMoveDescription_TeeterDance:: @ 84877BB
	.string "A wobbly dance\nthat confuses all\nthe POKéMON in\nbattle.$"

gMoveDescription_BlazeKick:: @ 84877F3
	.string "A fiery kick with a\nhigh critical-hit\nratio. It may also\nburn the foe.$"

gMoveDescription_MudSport:: @ 848783A
	.string "Weakens ELECTRIC-\ntype attacks while\nthe user is in the\nbattle.$"

gMoveDescription_IceBall:: @ 848787A
	.string "A 5-turn rolling\nattack that becomes\nstronger each time\nit rolls.$"

gMoveDescription_NeedleArm:: @ 84878BC
	.string "An attack using\nthorny arms.\nIt may make the\nfoe flinch.$"

gMoveDescription_SlackOff:: @ 84878F5
	.string "The user slacks off\nand restores its HP\nby half its full\nHP.$"

gMoveDescription_HyperVoice:: @ 8487932
	.string "The user lets loose\na horribly loud\nshout with the\npower to damage.$"

gMoveDescription_PoisonFang:: @ 8487976
	.string "The foe is bitten\nwith toxic fangs.\nIt may also badly\npoison the foe.$"

gMoveDescription_CrushClaw:: @ 84879BC
	.string "The foe is attacked\nwith sharp claws.\nIt may also lower\nthe foe's DEFENSE.$"

gMoveDescription_BlastBurn:: @ 8487A07
	.string "The foe is hit with\na huge explosion.\nThe user can't move\non the next turn.$"

gMoveDescription_HydroCannon:: @ 8487A53
	.string "The foe is hit with\na watery cannon.\nThe user can't move\non the next turn.$"

gMoveDescription_MeteorMash:: @ 8487A9E
	.string "The foe is hit with\na hard, fast punch.\nIt may also raise\nthe user's ATTACK.$"

gMoveDescription_Astonish:: @ 8487AEB
	.string "An attack using a\nstartling shout.\nIt also may make\nthe foe flinch.$"

gMoveDescription_WeatherBall:: @ 8487B2F
	.string "An attack that\nvaries in power and\ntype depending on\nthe weather.$"

gMoveDescription_Aromatherapy:: @ 8487B71
	.string "A soothing scent is\nreleased to heal\nall status problems\nin the user's party.$"

gMoveDescription_FakeTears:: @ 8487BBF
	.string "The user feigns\ncrying to sharply\nlower the foe's\nSP. DEF stat.$"

gMoveDescription_AirCutter:: @ 8487BFF
	.string "The foe is hit with\nrazor-like wind.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_Overheat:: @ 8487C46
	.string "An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.$"

gMoveDescription_OdorSleuth:: @ 8487C8B
	.string "Completely negates\nthe foe's efforts to\nheighten its ability\nto evade.$"

gMoveDescription_RockTomb:: @ 8487CD2
	.string "Boulders are hurled\nat the foe. It also\nlowers the foe's\nSPEED if it hits.$"

gMoveDescription_SilverWind:: @ 8487D1D
	.string "The foe is attacked\nwith a silver dust.\nIt may raise all\nthe user's stats.$"

gMoveDescription_MetalSound:: @ 8487D68
	.string "A horrible metallic\nscreech is used to\nsharply lower the\nfoe's SP. DEF.$"

gMoveDescription_GrassWhistle:: @ 8487DB0
	.string "A pleasant melody\nis played to lull\nthe foe into a deep\nsleep.$"

gMoveDescription_Tickle:: @ 8487DEF
	.string "The foe is made to\nlaugh, reducing its\nATTACK and DEFENSE\nstats.$"

gMoveDescription_CosmicPower:: @ 8487E30
	.string "The user absorbs a\nmystic power to\nraise its DEFENSE\nand SP. DEF.$"

gMoveDescription_WaterSpout:: @ 8487E72
	.string "The higher the\nuser's HP, the more\npowerful this\nattack becomes.$"

gMoveDescription_SignalBeam:: @ 8487EB3
	.string "The foe is hit with\na flashing beam\nthat may also\ncause confusion.$"

gMoveDescription_ShadowPunch:: @ 8487EF6
	.string "The user throws a\npunch from the\nshadows. It cannot\nbe evaded.$"

gMoveDescription_Extrasensory:: @ 8487F35
	.string "The user attacks\nwith an odd power\nthat may make the\nfoe flinch.$"

gMoveDescription_SkyUppercut:: @ 8487F76
	.string "The user attacks\nwith an uppercut\nthrown skywards\nwith force.$"

gMoveDescription_SandTomb:: @ 8487FB4
	.string "The foe is trapped\ninside a painful\nsandstorm for two\nto five turns.$"

gMoveDescription_SheerCold:: @ 8487FF9
	.string "The foe is attacked\nwith ultimate cold\nthat causes fainting\nif it hits.$"

gMoveDescription_MuddyWater:: @ 8488041
	.string "The user attacks\nwith muddy water.\nIt may also lower\nthe foe's accuracy.$"

gMoveDescription_BulletSeed:: @ 848808A
	.string "The user shoots\nseeds at the foe.\nTwo to five seeds\nare shot at once.$"

gMoveDescription_AerialAce:: @ 84880D0
	.string "An extremely fast\nattack against one\ntarget. It can't be\nevaded.$"

gMoveDescription_IcicleSpear:: @ 8488111
	.string "Sharp icicles are\nfired at the foe.\nIt strikes two to\nfive times.$"

gMoveDescription_IronDefense:: @ 8488153
	.string "The user hardens\nits body's surface\nto sharply raise its\nDEFENSE stat.$"

gMoveDescription_Block:: @ 848819A
	.string "The user blocks the\nfoe's way with arms\nspread wide to\nprevent escape.$"

gMoveDescription_Howl:: @ 84881E1
	.string "The user howls to\nraise its spirit and\nboost its ATTACK\nstat.$"

gMoveDescription_DragonClaw:: @ 848821F
	.string "Sharp, huge claws\nhook and slash the\nfoe quickly and\nwith great power.$"

gMoveDescription_FrenzyPlant:: @ 8488266
	.string "The foe is hit with\nan enormous branch.\nThe user can't move\non the next turn.$"

gMoveDescription_BulkUp:: @ 84882B4
	.string "The user bulks up\nits body to boost\nboth its ATTACK and\nDEFENSE stats.$"

gMoveDescription_Bounce:: @ 84882FB
	.string "The user bounces\non the foe on the\n2nd turn. It may\nparalyze the foe.$"

gMoveDescription_MudShot:: @ 8488341
	.string "The user attacks by\nhurling mud.\nIt also reduces the\nfoe's SPEED.$"

gMoveDescription_PoisonTail:: @ 8488383
	.string "An attack with a\nhigh critical-hit\nratio. It may also\npoison the foe.$"

gMoveDescription_Covet:: @ 84883C9
	.string "A cutely executed\nattack that also\nsteals the foe's\nhold item.$"

gMoveDescription_VoltTackle:: @ 8488408
	.string "The user throws an\nelectrified tackle.\nIt hurts the user\na little.$"

gMoveDescription_MagicalLeaf:: @ 848844B
	.string "The foe is attacked\nwith a strange leaf\nthat cannot be\nevaded.$"

gMoveDescription_WaterSport:: @ 848848A
	.string "Weakens FIRE-type\nattacks while the\nuser is in the\nbattle.$"

gMoveDescription_CalmMind:: @ 84884C5
	.string "The user focuses\nits mind to raise\nthe SP. ATK and\nSP. DEF stats.$"

gMoveDescription_LeafBlade:: @ 8488507
	.string "The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.$"

gMoveDescription_DragonDance:: @ 848854F
	.string "A mystic, powerful\ndance that boosts\nthe user's ATTACK\nand SPEED stats.$"

gMoveDescription_RockBlast:: @ 8488597
	.string "The user hurls two\nto five hard rocks\nat the foe to\nattack.$"

gMoveDescription_ShockWave:: @ 84885D3
	.string "A rapid jolt of\nelectricity strikes\nthe foe. It can't\nbe evaded.$"

gMoveDescription_WaterPulse:: @ 8488614
	.string "An attack with a\npulsing blast of\nwater. It may also\nconfuse the foe.$"

gMoveDescription_DoomDesire:: @ 848865A
	.string "A move that attacks\nthe foe with a\nblast of light two\nturns after use.$"

gMoveDescription_PsychoBoost:: @ 84886A1
	.string "An intense attack\nthat also sharply\nreduces the user's\nSP. ATK stat.$"

gMoveDescription_PoundSpa::
	.string "Golpea con las\npatas o la cola.$"

gMoveDescription_KarateChopSpa::
	.string "Da un golpe\ncortante.\nSuele ser crítico.$"

gMoveDescription_DoubleSlapSpa::
	.string "Abofetea de 2 a 5\nveces seguidas.$"

gMoveDescription_CometPunchSpa::
	.string "Pega de 2 a 5\nveces seguidas.$"

gMoveDescription_MegaPunchSpa::
	.string "Un puñetazo\nde gran potencia.$"

gMoveDescription_PayDaySpa::
	.string "Arroja monedas\nque luego\nrecupera.$"

gMoveDescription_FirePunchSpa::
	.string "Puñetazo ardiente.\nPuede quemar.$"

gMoveDescription_IcePunchSpa::
	.string "Puñetazo helado.\nPuede congelar.$"

gMoveDescription_ThunderPunchSpa::
	.string "Puñetazo eléctrico.\nPuede paralizar.$"

gMoveDescription_ScratchSpa::
	.string "Araña con afiladas\ngarras.$"

gMoveDescription_ViceGripSpa::
	.string "Atrapa con potentes\npinzas.$"

gMoveDescription_GuillotineSpa::
	.string "Pinzas que pueden\nderribar de un\ngolpe.$"

gMoveDescription_RazorWindSpa::
	.string "1.{SUPER_ER} turno:\nprepara.\n2.º: ataca.$"

gMoveDescription_SwordsDanceSpa::
	.string "Baile que mejora\nel ATAQUE.$"

gMoveDescription_CutSpa::
	.string "Corta con garras,\nguadañas, etc.\nFuera de combate\nse usa para cortar.$"

gMoveDescription_GustSpa::
	.string "Crea un tornado\ncon las alas.$"

gMoveDescription_WingAttackSpa::
	.string "Golpea al objetivo\ncon las alas.$"

gMoveDescription_WhirlwindSpa::
	.string "Se lleva al rival\ny termina el\ncombate.$"

gMoveDescription_FlySpa::
	.string "1.{SUPER_ER} turno: vuela.\n2.º: ataca. Fuera\nde combate lleva a\nsitios conocidos.$"

gMoveDescription_BindSpa::
	.string "Ata y oprime\nde 2 a 5 turnos.$"

gMoveDescription_SlamSpa::
	.string "Golpea con las\nextremidades.$"

gMoveDescription_VineWhipSpa::
	.string "Azota al enemigo\ncon ramas finas.$"

gMoveDescription_StompSpa::
	.string "Tremendo pisotón\nque puede causar\nretroceso.$"

gMoveDescription_DoubleKickSpa::
	.string "Una patada doble.\nGolpea 2 veces.$"

gMoveDescription_MegaKickSpa::
	.string "Patada de extrema\nfuerza.$"

gMoveDescription_JumpKickSpa::
	.string "Si falla, dañará\na quien lo usa.$"

gMoveDescription_RollingKickSpa::
	.string "Una patada rápida\ny circular.$"

gMoveDescription_SandAttackSpa::
	.string "Arroja arena\na la cara y baja\nla PRECISIÓN.$"

gMoveDescription_HeadbuttSpa::
	.string "Cabezazo que puede\nhacer retroceder\nal rival.$"

gMoveDescription_HornAttackSpa::
	.string "Ataca al enemigo\ncon afilados\ncuernos.$"

gMoveDescription_FuryAttackSpa::
	.string "Cornea al enemigo\nde 2 a 5 veces.$"

gMoveDescription_HornDrillSpa::
	.string "Ataque taladro.\nFulmina en 1 golpe.$"

gMoveDescription_TackleSpa::
	.string "Embiste con todo\nel cuerpo.$"

gMoveDescription_BodySlamSpa::
	.string "Ataque corporal\nque puede\nparalizar.$"

gMoveDescription_WrapSpa::
	.string "Oprime de 2 a 5\nturnos con ramas,\netc.$"

gMoveDescription_TakeDownSpa::
	.string "Carga desmedida\nque también hiere\nal agresor.$"

gMoveDescription_ThrashSpa::
	.string "Dura de 2 a 3\nturnos y acaba\nconfundiéndote.$"

gMoveDescription_DoubleEdgeSpa::
	.string "Ataque arriesgado\nque también hiere\nal agresor.$"

gMoveDescription_TailWhipSpa::
	.string "Agita la cola para\nbajar la DEFENSA\ndel otro.$"

gMoveDescription_PoisonStingSpa::
	.string "Puede envenenar al\nenemigo con púas,\netc.$"

gMoveDescription_TwineedleSpa::
	.string "Clava aguijones al\nrival 2 veces.$"

gMoveDescription_PinMissileSpa::
	.string "Lanza finas púas\nque hieren de 2 a\n5 veces.$"

gMoveDescription_LeerSpa::
	.string "Asusta al enemigo\npara bajar su\nDEFENSA.$"

gMoveDescription_BiteSpa::
	.string "Un voraz bocado\nque puede causar\nel retroceso.$"

gMoveDescription_GrowlSpa::
	.string "Dulce gruñido que\nreduce el ATAQUE\ndel otro.$"

gMoveDescription_RoarSpa::
	.string "Ahuyenta al rival\ny finaliza el\ncombate.$"

gMoveDescription_SingSpa::
	.string "Cancioncilla que\npuede dormir al\nenemigo.$"

gMoveDescription_SupersonicSpa::
	.string "Raras ondas sónicas\nque pueden\nconfundir.$"

gMoveDescription_SonicBoomSpa::
	.string "Lanza ondas de\nchoque que restan\n20 PS.$"

gMoveDescription_DisableSpa::
	.string "Desactiva un ataque\ndel contrincante.$"

gMoveDescription_AcidSpa::
	.string "Rocía corrosivo\nácido. Puede bajar\nla DEFENSA.$"

gMoveDescription_EmberSpa::
	.string "Ligero ataque que\npuede causar\nquemaduras.$"

gMoveDescription_FlamethrowerSpa::
	.string "Fuerte ataque que\npuede causar\nquemaduras.$"

gMoveDescription_MistSpa::
	.string "Te rodea de fina\nniebla y protege\ntus habilidades.$"

gMoveDescription_WaterGunSpa::
	.string "Rocía agua para\natacar.$"

gMoveDescription_HydroPumpSpa::
	.string "Lanza agua a\nchorros para\natacar.$"

gMoveDescription_SurfSpa::
	.string "Lanza una gran ola\nal rival.\nFuera de combate\nsirve para nadar.$"

gMoveDescription_IceBeamSpa::
	.string "Rayo de hielo\nque puede llegar\na congelar.$"

gMoveDescription_BlizzardSpa::
	.string "Tormenta de hielo\nque puede llegar\na congelar.$"

gMoveDescription_PsybeamSpa::
	.string "Extraño rayo\nque puede causar\nconfusión.$"

gMoveDescription_BubbleBeamSpa::
	.string "Diluvio de burbujas\nque puede bajar\nla VELOCIDAD.$"

gMoveDescription_AuroraBeamSpa::
	.string "Rayo multicolor\nque puede reducir\nel ATAQUE.$"

gMoveDescription_HyperBeamSpa::
	.string "Es eficaz, pero\ndeja inmóvil al\natacante 1 turno.$"

gMoveDescription_PeckSpa::
	.string "Ataca con un\npunzante pico.$"

gMoveDescription_DrillPeckSpa::
	.string "Picotazo giratorio\ny perforador muy\npotente.$"

gMoveDescription_SubmissionSpa::
	.string "Golpe desmedido\nque también hiere\nal agresor.$"

gMoveDescription_LowKickSpa::
	.string "Cuanto más pesa\nel enemigo, más\ndaño causa.$"

gMoveDescription_CounterSpa::
	.string "Devuelve un golpe\nfísico por\nduplicado.$"

gMoveDescription_SeismicTossSpa::
	.string "Se restarán tantos\nPS como nivel tenga\nel agresor.$"

gMoveDescription_StrengthSpa::
	.string "Potente ataque\nfísico. Fuera de\ncombate sirve para\nmover piedras.$"

gMoveDescription_AbsorbSpa::
	.string "Absorbe la\nmitad del daño\nproducido.$"

gMoveDescription_MegaDrainSpa::
	.string "Absorbe la mitad\ndel daño\nproducido.$"

gMoveDescription_LeechSeedSpa::
	.string "Planta tres semillas\nque quitan PS en\ncada turno.$"

gMoveDescription_GrowthSpa::
	.string "Crece a marchas\nforzadas y aumenta\nel AT. ESP.$"

gMoveDescription_RazorLeafSpa::
	.string "Corta con hojas.\nSuele ser crítico.$"

gMoveDescription_SolarBeamSpa::
	.string "1.{SUPER_ER} turno: absorbe\nluz.\n2.º: ataca.$"

gMoveDescription_PoisonPowderSpa::
	.string "Polvo tóxico que\npuede envenenar\nal enemigo.$"

gMoveDescription_StunSporeSpa::
	.string "Esparce polvo que\npuede paralizar\nal enemigo.$"

gMoveDescription_SleepPowderSpa::
	.string "Esparce polvo que\npuede dormir al\nenemigo.$"

gMoveDescription_PetalDanceSpa::
	.string "Dura de 2 a 3\nturnos y acaba\nconfundiéndote.$"

gMoveDescription_StringShotSpa::
	.string "Baja la VELOCIDAD\ndel enemigo.$"

gMoveDescription_DragonRageSpa::
	.string "Cadena de ondas de\nchoque que quitan\n40 PS.$"

gMoveDescription_FireSpinSpa::
	.string "Un aro de fuego\nque atrapa de 2\na 5 veces.$"

gMoveDescription_ThunderShockSpa::
	.string "Ataque eléctrico\nque puede\nparalizar al\nenemigo.$"

gMoveDescription_ThunderboltSpa::
	.string "Duro ataque\neléctrico que\npuede paralizar\nal enemigo.$"

gMoveDescription_ThunderWaveSpa::
	.string "Una descarga que\npuede paralizar\nal enemigo.$"

gMoveDescription_ThunderSpa::
	.string "Un estruendo que\npuede paralizar\nal enemigo.$"

gMoveDescription_RockThrowSpa::
	.string "Tira pequeñas rocas\nal enemigo.$"

gMoveDescription_EarthquakeSpa::
	.string "Fuerte, pero inútil\ncontra voladores.$"

gMoveDescription_FissureSpa::
	.string "Ataque de tierra.\nFulmina en 1 golpe.$"

gMoveDescription_DigSpa::
	.string "1.{SUPER_ER} turno: cava.\n2.º: ataca.$"

gMoveDescription_ToxicSpa::
	.string "Envenena al rival\nde forma\nprogresiva.$"

gMoveDescription_ConfusionSpa::
	.string "Ataque psíquico\nque puede causar\nconfusión.$"

gMoveDescription_PsychicSpa::
	.string "Fuerte ataque\npsíquico que\npuede bajar\nla DEF. ESP.$"

gMoveDescription_HypnosisSpa::
	.string "Ataque hipnótico\nque puede dormir\nal enemigo.$"

gMoveDescription_MeditateSpa::
	.string "Reposa y medita\npara aumentar\nel ATAQUE.$"

gMoveDescription_AgilitySpa::
	.string "Relaja el cuerpo\npara ganar\nVELOCIDAD.$"

gMoveDescription_QuickAttackSpa::
	.string "Ataque rápido que\npermite golpear\nen 1.{SUPER_ER} lugar.$"

gMoveDescription_RageSpa::
	.string "Mejora tu ATAQUE\ncada vez que te\ngolpean.$"

gMoveDescription_TeleportSpa::
	.string "Movimiento psíquico\nque permite huir\nal instante.$"

gMoveDescription_NightShadeSpa::
	.string "Se restarán tantos\nPS como nivel tenga\nel agresor.$"

gMoveDescription_MimicSpa::
	.string "Copia un ataque\nusado por el\nenemigo.$"

gMoveDescription_ScreechSpa::
	.string "Ruido agudo que\nbaja mucho\nla DEFENSA\ndel rival.$"

gMoveDescription_DoubleTeamSpa::
	.string "Crea espejismos\npara mejorar\nla EVASIÓN.$"

gMoveDescription_RecoverSpa::
	.string "Restaura hasta\nla mitad de los PS\nmáximos.$"

gMoveDescription_HardenSpa::
	.string "Tensa la\nmusculatura\npara aumentar\nla DEFENSA.$"

gMoveDescription_MinimizeSpa::
	.string "El agresor mengua\npara aumentar\nla EVASIÓN.$"

gMoveDescription_SmokescreenSpa::
	.string "Baja la PRECISIÓN\ndel enemigo con\nhumo, etc.$"

gMoveDescription_ConfuseRaySpa::
	.string "Rayo siniestro\nque confunde\nal enemigo.$"

gMoveDescription_WithdrawSpa::
	.string "El agresor se\nprotege en su\ncoraza y sube\nla DEFENSA.$"

gMoveDescription_DefenseCurlSpa::
	.string "Oculta su punto\ndébil al rizarse.\nSube la DEFENSA.$"

gMoveDescription_BarrierSpa::
	.string "Crea una barrera\npara subir mucho\nla DEFENSA.$"

gMoveDescription_LightScreenSpa::
	.string "Reduce el daño que\ncausa el AT. ESP.\ndel rival.$"

gMoveDescription_HazeSpa::
	.string "Nube negra que\nelimina los cambios\nde características.$"

gMoveDescription_ReflectSpa::
	.string "Pared de luz\nque debilita los\nataques físicos.$"

gMoveDescription_FocusEnergySpa::
	.string "Concentra energía\npara asegurar\nun golpe crítico.$"

gMoveDescription_BideSpa::
	.string "Espera 2 turnos\npara atacar con\ndoble potencia.$"

gMoveDescription_MetronomeSpa::
	.string "Usa al azar un\nataque POKéMON.$"

gMoveDescription_MirrorMoveSpa::
	.string "Contraataca\ncon el mismo\nmovimiento.$"

gMoveDescription_SelfDestructSpa::
	.string "Potente, pero hace\nque te debilites.$"

gMoveDescription_EggBombSpa::
	.string "Arroja un huevo\nal enemigo.$"

gMoveDescription_LickSpa::
	.string "Usa la lengua para\natacar. Puede\ncausar parálisis.$"

gMoveDescription_SmogSpa::
	.string "Gases de escape\nque pueden llegar\na envenenar.$"

gMoveDescription_SludgeSpa::
	.string "Arroja residuos\nal rival. Puede\nllegar a envenenar.$"

gMoveDescription_BoneClubSpa::
	.string "Aporrea con\nun hueso.\nPuede causar\nel retroceso.$"

gMoveDescription_FireBlastSpa::
	.string "Llama que lo\nchamusca todo\ny suele causar\nquemadura.$"

gMoveDescription_WaterfallSpa::
	.string "Embiste con impulso\npara remontar\nuna cascada incluso\nfuera de combate.$"

gMoveDescription_ClampSpa::
	.string "Atrapa y atenaza\ncon fuerza de 2\na 5 turnos.$"

gMoveDescription_SwiftSpa::
	.string "Lanza rayos en\nforma de estrella\nque no fallan.$"

gMoveDescription_SkullBashSpa::
	.string "1.{SUPER_ER} turno: se\nprepara.\n2.º: da\nel cabezazo.$"

gMoveDescription_SpikeCannonSpa::
	.string "Lanza finas púas\nque hieren de 2\na 5 veces.$"

gMoveDescription_ConstrictSpa::
	.string "Constriñe\npara herir\ny puede bajar\nla VELOCIDAD.$"

gMoveDescription_AmnesiaSpa::
	.string "Olvida algo\ny aumenta mucho\nla DEFENSA ESP.$"

gMoveDescription_KinesisSpa::
	.string "Distrae al rival\ny baja su nivel\nde PRECISIÓN.$"

gMoveDescription_SoftBoiledSpa::
	.string "Restaura hasta\nla mitad de tus PS\nmáximos.$"

gMoveDescription_HiJumpKickSpa::
	.string "Si fallas esta\npatada, puedes\nautolesionarte.$"

gMoveDescription_GlareSpa::
	.string "Intimida y asusta\nal rival hasta\ndejarlo paralizado.$"

gMoveDescription_DreamEaterSpa::
	.string "Roba la mitad\ndel daño causado\na un rival dormido.$"

gMoveDescription_PoisonGasSpa::
	.string "Envuelve al enemigo\nen gas tóxico\nvenenoso.$"

gMoveDescription_BarrageSpa::
	.string "Arroja esferas\nal rival de 2\na 5 veces.$"

gMoveDescription_LeechLifeSpa::
	.string "Absorbe la\nmitad del daño\nproducido.$"

gMoveDescription_LovelyKissSpa::
	.string "Pide un beso con\nuna cara que\nasusta y adormece.$"

gMoveDescription_SkyAttackSpa::
	.string "1.º, busca punto\nflaco.\n2.º, va a por él.$"

gMoveDescription_TransformSpa::
	.string "Modifica las\ncélulas del rival\ny lo clona.$"

gMoveDescription_BubbleSpa::
	.string "Usa burbujas para\nintentar bajar\nla VELOCIDAD.$"

gMoveDescription_DizzyPunchSpa::
	.string "Puño repetitivo\nque puede\ncausar confusión.$"

gMoveDescription_SporeSpa::
	.string "Esparce esporas\nque inducen\nal sueño.$"

gMoveDescription_FlashSpa::
	.string "Luz cegadora que\nbaja la PRECISIÓN.\nFuera de combate\nsirve para iluminar.$"

gMoveDescription_PsywaveSpa::
	.string "Ataque con\nonda psíquica\nde intensidad\nvariable.$"

gMoveDescription_SplashSpa::
	.string "No tiene ningún\nefecto.\nSólo salpica.$"

gMoveDescription_AcidArmorSpa::
	.string "Te hace líquido\ny aumenta\nbastante\ntu DEFENSA.$"

gMoveDescription_CrabhammerSpa::
	.string "Pinza con fuerza\ny suele dar un\ngolpe crítico.$"

gMoveDescription_ExplosionSpa::
	.string "Causa mucho daño,\npero te debilita.$"

gMoveDescription_FurySwipesSpa::
	.string "Araña rápidamente\nde 2 a 5 veces.$"

gMoveDescription_BonemerangSpa::
	.string "Lanza un hueso\na modo de bumerán,\nque da 2 veces.$"

gMoveDescription_RestSpa::
	.string "Te duerme durante\n2 turnos para\ncurarte totalmente.$"

gMoveDescription_RockSlideSpa::
	.string "Lanza grandes\npedruscos.\nPuede causar\nretroceso.$"

gMoveDescription_HyperFangSpa::
	.string "Ataque con finos\ncolmillos. Puede\ncausar retroceso.$"

gMoveDescription_SharpenSpa::
	.string "Mejora el ATAQUE\nde quien lo usa.$"

gMoveDescription_ConversionSpa::
	.string "Cambia tu tipo\npor el tipo de un\nataque que tengas.$"

gMoveDescription_TriAttackSpa::
	.string "Dispara 3 tipos\nde rayos a la vez.$"

gMoveDescription_SuperFangSpa::
	.string "Finos colmillos\nque bajan a la\nmitad los PS\ndel rival.$"

gMoveDescription_SlashSpa::
	.string "Acuchilla con\npinzas, etc.\nSuele dar\nun golpe crítico.$"

gMoveDescription_SubstituteSpa::
	.string "Crea un señuelo\ncon 1/4 de tus\nPS máximos.$"

gMoveDescription_StruggleSpa::
	.string "Sólo se usa al\nacabarse los PP.\nTe hiere un poco.$"

gMoveDescription_SketchSpa::
	.string "Copia siempre\nel último ataque\ndel rival.$"

gMoveDescription_TripleKickSpa::
	.string "Patea 3 veces\nseguidas y cada\nvez más fuerte.$"

gMoveDescription_ThiefSpa::
	.string "Puede quitarle\nal rival el objeto\nque lleve.$"

gMoveDescription_SpiderWebSpa::
	.string "Enreda al rival\npara evitar que\nhuya o pida\nel relevo.$"

gMoveDescription_MindReaderSpa::
	.string "Adivina el ataque\ndel otro y actúa\nen consecuencia.$"

gMoveDescription_NightmareSpa::
	.string "El rival dormido\npierde 1/4 de PS\npor turno.$"

gMoveDescription_FlameWheelSpa::
	.string "Ataque de fuego\nque puede causar\nquemaduras.$"

gMoveDescription_SnoreSpa::
	.string "Fuerte ronquido\nque puede usarse\nestando dormido.$"

gMoveDescription_CurseSpa::
	.string "En el tipo\nFANTASMA tiene\nun efecto distinto.$"

gMoveDescription_FlailSpa::
	.string "Causa un daño\nmayor si tienes\npocos PS.$"

gMoveDescription_Conversion2Spa::
	.string "Tu tipo se hace\nresistente al último\ntipo de ataque.$"

gMoveDescription_AeroblastSpa::
	.string "Lanza un chorro\nde aire que suele\ndar un golpe\ncrítico.$"

gMoveDescription_CottonSporeSpa::
	.string "Le pega esporas\nal rival para\nreducir su\nVELOCIDAD.$"

gMoveDescription_ReversalSpa::
	.string "Si tienes pocos PS,\nel daño que causa\nes mucho mayor.$"

gMoveDescription_SpiteSpa::
	.string "Baja con rencor\nPP del último\nataque recibido.$"

gMoveDescription_PowderSnowSpa::
	.string "Lanza una nevada\nque puede llegar\na congelar.$"

gMoveDescription_ProtectSpa::
	.string "Frena ataques,\npero puede fallar\nsi se usa sin cesar.$"

gMoveDescription_MachPunchSpa::
	.string "Puñetazo que se da\nrápido para golpear\nprimero.$"

gMoveDescription_ScaryFaceSpa::
	.string "Asusta al enemigo\npara bajarle\nVELOCIDAD.$"

gMoveDescription_FaintAttackSpa::
	.string "Acerca al enemigo\npara que el golpe\nno falle.$"

gMoveDescription_SweetKissSpa::
	.string "Pide un beso con\ndulzura y suele\ncausar confusión.$"

gMoveDescription_BellyDrumSpa::
	.string "Reduce tus PS para\nmejorar el ATAQUE.$"

gMoveDescription_SludgeBombSpa::
	.string "Explosión de lodo\nque puede llegar\na envenenar.$"

gMoveDescription_MudSlapSpa::
	.string "Echa lodo en la\ncara para bajar\nla PRECISIÓN.$"

gMoveDescription_OctazookaSpa::
	.string "Dispara tinta para\natacar y bajar\nla PRECISIÓN.$"

gMoveDescription_SpikesSpa::
	.string "Riega púas que\nhieren si el rival\npide el relevo.$"

gMoveDescription_ZapCannonSpa::
	.string "No es certero,\npero causa\nparálisis si atina.$"

gMoveDescription_ForesightSpa::
	.string "Anula los intentos\ndel rival de\naumentar\nla EVASIÓN.$"

gMoveDescription_DestinyBondSpa::
	.string "Si te debilitas,\nel enemigo\nse debilita\ncontigo.$"

gMoveDescription_PerishSongSpa::
	.string "A los 3 turnos\ndel canto, caen\nrival y atacante.$"

gMoveDescription_IcyWindSpa::
	.string "Ataque helado que\nbaja la VELOCIDAD.$"

gMoveDescription_DetectSpa::
	.string "Frena ataques,\npero puede\nfallar si se usa\nsin parar.$"

gMoveDescription_BoneRushSpa::
	.string "Hueso en ristre,\naporrea al enemigo\nde 2 a 5 veces.$"

gMoveDescription_LockOnSpa::
	.string "Fija el blanco para\nque el siguiente\nataque no falle.$"

gMoveDescription_OutrageSpa::
	.string "Embestida que dura\n2 ó 3 turnos y te\nconfunde.$"

gMoveDescription_SandstormSpa::
	.string "Tormenta de arena\nque dura varios\nturnos.$"

gMoveDescription_GigaDrainSpa::
	.string "Absorbe la\nmitad del daño\nproducido.$"

gMoveDescription_EndureSpa::
	.string "Resiste el ataque\nde 1 turno y deja\nal menos 1 PS.$"

gMoveDescription_CharmSpa::
	.string "Engatusa al rival\ny reduce bastante\nsu ATAQUE.$"

gMoveDescription_RolloutSpa::
	.string "Ataque de 5 turnos,\ncon fuerza cada\nvez mayor.$"

gMoveDescription_FalseSwipeSpa::
	.string "Deja al enemigo\ncon al menos 1 PS.$"

gMoveDescription_SwaggerSpa::
	.string "Provoca confusión,\npero también sube\nel ATAQUE.$"

gMoveDescription_MilkDrinkSpa::
	.string "Restaura hasta\nla mitad de tus PS\nmáximos.$"

gMoveDescription_SparkSpa::
	.string "Ataque eléctrico\nque puede\nllegar a paralizar.$"

gMoveDescription_FuryCutterSpa::
	.string "Crece en intensidad\nsi se usa repetidas\nveces.$"

gMoveDescription_SteelWingSpa::
	.string "Alas rígidas que\ngolpean al rival.$"

gMoveDescription_MeanLookSpa::
	.string "Mal de ojo que\nimpide al rival huir\no pedir el relevo.$"

gMoveDescription_AttractSpa::
	.string "Reduce la\nposibilidad de que\nel enemigo ataque.$"

gMoveDescription_SleepTalkSpa::
	.string "Mientras duerme,\nusa un ataque\nelegido al azar.$"

gMoveDescription_HealBellSpa::
	.string "Repicar que cura\nlos problemas\nde estado.$"

gMoveDescription_ReturnSpa::
	.string "Ataque que aumenta\nsus efectos con\nla amistad.$"

gMoveDescription_PresentSpa::
	.string "Regalo con forma\nde bomba. Puede\nque restaure\nlos PS.$"

gMoveDescription_FrustrationSpa::
	.string "Es más fuerte si\nno se aprecia\nal ENTRENADOR.$"

gMoveDescription_SafeguardSpa::
	.string "Fuerza mística\nque evita\nproblemas\nde estado.$"

gMoveDescription_PainSplitSpa::
	.string "Une tus PS a los\ndel rival y los\nreparte por igual.$"

gMoveDescription_SacredFireSpa::
	.string "Fuego místico que\npuede causar\nquemaduras.$"

gMoveDescription_MagnitudeSpa::
	.string "Sacudida sísmica\nde intensidad\nvariable.$"

gMoveDescription_DynamicPunchSpa::
	.string "No es certero,\npero causa\nconfusión si atina.$"

gMoveDescription_MegahornSpa::
	.string "Violenta embestida\ncon retorcidos\ncuernos.$"

gMoveDescription_DragonBreathSpa::
	.string "Fuerte ráfaga\nde aliento\nque golpea\nal enemigo.$"

gMoveDescription_BatonPassSpa::
	.string "Cambia de\ncompañero y\nmantiene\nlos estados.$"

gMoveDescription_EncoreSpa::
	.string "El rival repite\nel último ataque\nde 2 a 6 veces.$"

gMoveDescription_PursuitSpa::
	.string "Hace mucho daño\nal rival que pide\nel relevo.$"

gMoveDescription_RapidSpinSpa::
	.string "Ataque corporal\ngiratorio de gran\nvelocidad.$"

gMoveDescription_SweetScentSpa::
	.string "Engatusa al rival\npara reducir\nsu EVASIÓN.$"

gMoveDescription_IronTailSpa::
	.string "Ataca con una\ncola férrea\ny puede bajar\nla DEFENSA.$"

gMoveDescription_MetalClawSpa::
	.string "Ataque con garra\nque puede\naumentar\ntu ATAQUE.$"

gMoveDescription_VitalThrowSpa::
	.string "Lleva su tiempo\npero no falla.$"

gMoveDescription_MorningSunSpa::
	.string "Restaura PS.\nLa cantidad\nvaría según\nel clima.$"

gMoveDescription_SynthesisSpa::
	.string "Restaura PS.\nLa cantidad\nvaría según\nel clima.$"

gMoveDescription_MoonlightSpa::
	.string "Restaura PS.\nLa cantidad\nvaría según\nel clima.$"

gMoveDescription_HiddenPowerSpa::
	.string "Su eficacia varía\nsegún el agresor.$"

gMoveDescription_CrossChopSpa::
	.string "Corte doble que\nsuele propinar\nun golpe crítico.$"

gMoveDescription_TwisterSpa::
	.string "Crea un violento\ntornado para hacer\ntrizas al rival.$"

gMoveDescription_RainDanceSpa::
	.string "Refuerza los\nataques de\ntipo AGUA\ndurante 5 turnos.$"

gMoveDescription_SunnyDaySpa::
	.string "Sube los ataques\nde tipo FUEGO\ndurante 5 turnos.$"

gMoveDescription_CrunchSpa::
	.string "Tritura con finos\ncolmillos y puede\nbajar la DEF. ESP.$"

gMoveDescription_MirrorCoatSpa::
	.string "Responde a un\nATAQUE ESPECIAL\ncon doble fuerza.$"

gMoveDescription_PsychUpSpa::
	.string "Copia los efectos\ndel rival y te los\nadjudica.$"

gMoveDescription_ExtremeSpeedSpa::
	.string "Ataque extrema-\ndamente rápido\ny demoledor.$"

gMoveDescription_AncientPowerSpa::
	.string "Puede subir\ntodas las\ncaracterísticas.$"

gMoveDescription_ShadowBallSpa::
	.string "Lanza una bola\nnegra que puede\nbajar la DEF. ESP.$"

gMoveDescription_FutureSightSpa::
	.string "Aumenta la energía\ninterior para\ngolpear a los 2\nturnos.$"

gMoveDescription_RockSmashSpa::
	.string "Ataque que puede\nbajar la DEFENSA.\nFuera de combate\nmachaca rocas.$"

gMoveDescription_WhirlpoolSpa::
	.string "Atrapa y daña\nal rival de 2 a 5\nturnos con un\ntorbellino.$"

gMoveDescription_BeatUpSpa::
	.string "Ataque de todo el\nequipo POKéMON.$"

gMoveDescription_FakeOutSpa::
	.string "Ataca primero\nen un turno\ny puede causar\nretroceso.$"

gMoveDescription_UproarSpa::
	.string "Alborota de 2 a 5\nturnos. Mantiene\ndespierto.$"

gMoveDescription_StockpileSpa::
	.string "Recarga energía\nhasta 3 veces.$"

gMoveDescription_SpitUpSpa::
	.string "Libera energía\nacumulada.\nCuanta más, mejor.$"

gMoveDescription_SwallowSpa::
	.string "Absorbe energía\nacumulada\ny restaura PS.$"

gMoveDescription_HeatWaveSpa::
	.string "Exhala un vaho\nígneo que puede\nquemar al rival.$"

gMoveDescription_HailSpa::
	.string "Tormenta de granizo\nque golpea en cada\nturno.$"

gMoveDescription_TormentSpa::
	.string "Agobia e impide\nel uso reiterado\nde un ataque.$"

gMoveDescription_FlatterSpa::
	.string "Confunde al rival,\npero sube su AT.\nESP.$"

gMoveDescription_WillOWispSpa::
	.string "Fuego muy intenso\nque produce\nquemaduras.$"

gMoveDescription_MementoSpa::
	.string "Baja las\nhabilidades\ndel rival\ny te fulmina.$"

gMoveDescription_FacadeSpa::
	.string "Potencia el ATAQUE\nal estar quemado,\nparalizado o\nenvenenado.$"

gMoveDescription_FocusPunchSpa::
	.string "Es tardío, pero\nsi el rival\nte golpea\nno te moverás.$"

gMoveDescription_SmellingSaltSpa::
	.string "Afecta a rivales\nparalizados, pero\ntambién los cura.$"

gMoveDescription_FollowMeSpa::
	.string "Llama la atención\npara concentrar\nlos ataques.$"

gMoveDescription_NaturePowerSpa::
	.string "El tipo de ataque\nvaría según\nel sitio.$"

gMoveDescription_ChargeSpa::
	.string "Recarga energía\ny sube el ataque\neléctrico posterior.$"

gMoveDescription_TauntSpa::
	.string "Hace que el rival\nsólo use ataques.$"

gMoveDescription_HelpingHandSpa::
	.string "Refuerza los\nmovimientos\ndel receptor.$"

gMoveDescription_TrickSpa::
	.string "Engaña al rival\ny provoca\nun cambio\nde objeto.$"

gMoveDescription_RolePlaySpa::
	.string "Imita al rival\ny copia\nsu HABILIDAD\nESPECIAL.$"

gMoveDescription_WishSpa::
	.string "Lleva tiempo, pero\ncumple el deseo\nde restaurar\nlos PS.$"

gMoveDescription_AssistSpa::
	.string "Ataque elegido\nal azar de un\nmiembro del equipo.$"

gMoveDescription_IngrainSpa::
	.string "Echa raíces para\nrecuperar PS,\npero impide\nel relevo.$"

gMoveDescription_SuperpowerSpa::
	.string "Aumenta mucho\nla fuerza, pero las\nhabilidades bajan.$"

gMoveDescription_MagicCoatSpa::
	.string "El agresor recibe\nel reflejo de los\nefectos especiales.$"

gMoveDescription_RecycleSpa::
	.string "Recicla un objeto\nusado para\nutilizarlo de\nnuevo.$"

gMoveDescription_RevengeSpa::
	.string "Ataque que\ngana fuerza si\nel enemigo\nte hiere.$"

gMoveDescription_BrickBreakSpa::
	.string "Destruye barreras\ncomo REFLEJO\ny causa daño.$"

gMoveDescription_YawnSpa::
	.string "Provoca el bostezo\ny después\nel sueño.$"

gMoveDescription_KnockOffSpa::
	.string "Deja al rival\ndesprovisto\ndel objeto\nque lleva.$"

gMoveDescription_EndeavorSpa::
	.string "Gana fuerza si\nel atacante\ntiene menos\nPS que el rival.$"

gMoveDescription_EruptionSpa::
	.string "Cuanto mayor\nsea el número\nde tus PS, más\ndaño harás.$"

gMoveDescription_SkillSwapSpa::
	.string "Intercambia la\nhabilidad especial\ncon otro POKéMON.$"

gMoveDescription_ImprisonSpa::
	.string "Impide al rival\nusar ataques\nque tú conoces.$"

gMoveDescription_RefreshSpa::
	.string "Cura envenena-\nmientos, parálisis\ny quemaduras.$"

gMoveDescription_GrudgeSpa::
	.string "Si te debilitas,\nborra los PP\ndel último ataque\ndel rival.$"

gMoveDescription_SnatchSpa::
	.string "Roba el efecto\ndel ataque\nque el rival\nuse después.$"

gMoveDescription_SecretPowerSpa::
	.string "Los efectos de este\nataque varían\nsegún la zona.$"

gMoveDescription_DiveSpa::
	.string "1.{SUPER_ER} turno: bucea.\n2.º: golpea.$"

gMoveDescription_ArmThrustSpa::
	.string "Se dan puñetazos\ndirectos de 2\na 5 turnos.$"

gMoveDescription_CamouflageSpa::
	.string "Modifica el tipo\ndel POKéMON\nsegún la zona\ndonde esté.$"

gMoveDescription_TailGlowSpa::
	.string "Ráfaga de luz\nque sube\nmuchísimo\nel AT. ESP.$"

gMoveDescription_LusterPurgeSpa::
	.string "Fogonazo de luz\nque puede\nbajar la DEF. ESP.$"

gMoveDescription_MistBallSpa::
	.string "Banco de niebla\nque puede bajar\nel AT. ESP.$"

gMoveDescription_FeatherDanceSpa::
	.string "Envuelve al rival\ncon plumón\npara reducir\nsu ATAQUE.$"

gMoveDescription_TeeterDanceSpa::
	.string "Confunde a todos\nlos POKéMON\nque hay en escena.$"

gMoveDescription_BlazeKickSpa::
	.string "Suele ser un golpe\ncrítico y causar\nquemaduras.$"

gMoveDescription_MudSportSpa::
	.string "Te cubre de lodo\ny mejora\ntu resistencia\neléctrica.$"

gMoveDescription_IceBallSpa::
	.string "Dura 5 turnos\ny gana fuerza\nen cada uno.$"

gMoveDescription_NeedleArmSpa::
	.string "Pega con brazos\nde pinchos\ny puede causar\nretroceso.$"

gMoveDescription_SlackOffSpa::
	.string "Te relaja y\nrestaura la\nmitad de los\nPS máximos.$"

gMoveDescription_HyperVoiceSpa::
	.string "Ondas sonoras\nde alta frecuencia\nque hieren.$"

gMoveDescription_PoisonFangSpa::
	.string "Incisivos colmillos\nque pueden\nenvenenar al rival.$"

gMoveDescription_CrushClawSpa::
	.string "Hace trizas al\nenemigo y puede\nbajar la DEFENSA.$"

gMoveDescription_BlastBurnSpa::
	.string "Es muy eficaz,\npero te inmoviliza\n1 turno.$"

gMoveDescription_HydroCannonSpa::
	.string "Es muy eficaz,\npero te inmoviliza\n1 turno.$"

gMoveDescription_MeteorMashSpa::
	.string "Impacta como\nun meteorito\ny suele subir\nel ATAQUE.$"

gMoveDescription_AstonishSpa::
	.string "Impresiona tanto\nque puede\nhacer retroceder\nal rival.$"

gMoveDescription_WeatherBallSpa::
	.string "El tipo y fuerza\ndel ataque\nvarían según\nel clima.$"

gMoveDescription_AromatherapySpa::
	.string "Cura todos los\nproblemas de\nestado con\nun suave aroma.$"

gMoveDescription_FakeTearsSpa::
	.string "Lágrimas de\ncocodrilo que\nbajan mucho\nla DEF. ESP.$"

gMoveDescription_AirCutterSpa::
	.string "Viento cortante\nque azota.\nSuele ser\nun golpe crítico.$"

gMoveDescription_OverheatSpa::
	.string "Ataque en toda\nregla que\nbaja mucho\ntu AT. ESP.$"

gMoveDescription_OdorSleuthSpa::
	.string "Anula los intentos\ndel rival por\naumentar\nla EVASIÓN.$"

gMoveDescription_RockTombSpa::
	.string "Tira rocas al\nrival, lo para\ny suele bajarle\nVELOCIDAD.$"

gMoveDescription_SilverWindSpa::
	.string "Partículas de plata\nque quizá suban\nlas habilidades.$"

gMoveDescription_MetalSoundSpa::
	.string "Tremendo chirrido\nque baja mucho\nla DEF. ESP.$"

gMoveDescription_GrassWhistleSpa::
	.string "Agradable melodía\nque adormece\nal rival.$"

gMoveDescription_TickleSpa::
	.string "Hace reír para\nbajar el ATAQUE\ny la DEFENSA.$"

gMoveDescription_CosmicPowerSpa::
	.string "Sube la DEFENSA\ny la DEF. ESP. con\nenergía mística.$"

gMoveDescription_WaterSpoutSpa::
	.string "Si tienes muchos\nPS, el daño que\ncausa es mucho\nmayor.$"

gMoveDescription_SignalBeamSpa::
	.string "Extraño ataque\ncon rayo.\nPuede causar\nconfusión.$"

gMoveDescription_ShadowPunchSpa::
	.string "Puñetazo ineludible\nprocedente de las\nsombras.$"

gMoveDescription_ExtrasensorySpa::
	.string "Energía muy\nextraña que\npuede causar\nel retroceso.$"

gMoveDescription_SkyUppercutSpa::
	.string "Gancho ascendente\nde gran ímpetu.$"

gMoveDescription_SandTombSpa::
	.string "Enreda en un\nremolino de arena\nde 2 a 5 turnos.$"

gMoveDescription_SheerColdSpa::
	.string "Ataque polar\nque debilita\nal rival si le\nalcanza.$"

gMoveDescription_MuddyWaterSpa::
	.string "Ataque con agua\nlodosa que puede\nbajar la\nPRECISIÓN.$"

gMoveDescription_BulletSeedSpa::
	.string "Dispara de 2 a 5\nráfagas consecu-\ntivas de semillas.$"

gMoveDescription_AerialAceSpa::
	.string "Ataque tremenda-\nmente rápido\ne ineludible.$"

gMoveDescription_IcicleSpearSpa::
	.string "Ataca lanzando\nde 2 a 5 ráfagas\nde carámbanos.$"

gMoveDescription_IronDefenseSpa::
	.string "Te fortalece y\nsube mucho\nla DEFENSA.$"

gMoveDescription_BlockSpa::
	.string "Le corta el paso\nal rival para que\nno pueda escapar.$"

gMoveDescription_HowlSpa::
	.string "Aullido que sube\nel ánimo y aumenta\nel ATAQUE.$"

gMoveDescription_DragonClawSpa::
	.string "Araña al rival\ncon garras\nafiladas.$"

gMoveDescription_FrenzyPlantSpa::
	.string "Es eficaz, pero\ndeja inmóvil al\nagresor 1 turno.$"

gMoveDescription_BulkUpSpa::
	.string "Robustece el\ncuerpo para\nsubir ATAQUE\ny DEFENSA.$"

gMoveDescription_BounceSpa::
	.string "1.{SUPER_ER} turno: bota.\n2.º: golpea.\nPuede paralizar.$"

gMoveDescription_MudShotSpa::
	.string "Dispara lodo\nal rival y reduce\nsu VELOCIDAD.$"

gMoveDescription_PoisonTailSpa::
	.string "Puede envenenar\ny dar un golpe\ncrítico.$"

gMoveDescription_CovetSpa::
	.string "Pide con ternura\nal rival el objeto\nque lleve.$"

gMoveDescription_VoltTackleSpa::
	.string "Placaje de alto\nriesgo que hiere\nun poco al\natacante.$"

gMoveDescription_MagicalLeafSpa::
	.string "Ataca con una\nextraña hoja\nque no se puede\nesquivar.$"

gMoveDescription_WaterSportSpa::
	.string "Te moja para\nque resistas\nmás los ataques\nde fuego.$"

gMoveDescription_CalmMindSpa::
	.string "Sube el AT. ESP.\ny la DEF. ESP.\ncon concentración.$"

gMoveDescription_LeafBladeSpa::
	.string "Acuchilla con\nuna hoja fina.\nSuele dar\nun golpe crítico.$"

gMoveDescription_DragonDanceSpa::
	.string "Danza mística\nque sube\nel ATAQUE\ny la VELOCIDAD.$"

gMoveDescription_RockBlastSpa::
	.string "Lanza pedruscos\nal rival de 2 a 5\nveces consecutivas.$"

gMoveDescription_ShockWaveSpa::
	.string "Ataque eléctrico\nmuy rápido\ne ineludible.$"

gMoveDescription_WaterPulseSpa::
	.string "Ondas ultrasónicas\nque pueden\nconfundir al rival.$"

gMoveDescription_DoomDesireSpa::
	.string "Concentra intensa\nluz solar y ataca\n2 turnos después.$"

gMoveDescription_PsychoBoostSpa::
	.string "Es tremendamente\npotente, pero baja\nmucho el AT. ESP.$"
