gText_NewName:: @ 81C574F
    .string "New Name$"

gText_NameChoice_Green:: @ 81C5758
    .string "Green$"

gText_NameChoice_Red:: @ 81C575E
    .string "Red$"

gText_NameChoice_Leaf:: @ 81C5762
    .string "Leaf$"

gText_NameChoice_Fire:: @ 81C5767
    .string "Fire$"

gText_NameChoice_Gary:: @ 81C576C
    .string "Gary$"

gText_NameChoice_Kaz:: @ 81C5771
    .string "Kaz$"

gText_NameChoice_Toru:: @ 81C5775
    .string "Toru$"

gText_NameChoice_Ash:: @ 81C577A
    .string "Ash$"

gText_NameChoice_Kene:: @ 81C577E
    .string "Kene$"

gText_NameChoice_Geki:: @ 81C5783
    .string "Geki$"

gText_NameChoice_Jak:: @ 81C5788
    .string "Jak$"

gText_NameChoice_Janne:: @ 81C578C
    .string "Janne$"

gText_NameChoice_Jonn:: @ 81C5792
    .string "Jonn$"

gText_NameChoice_Kamon:: @ 81C5797
    .string "Kamon$"

gText_NameChoice_Karl:: @ 81C579D
    .string "Karl$"

gText_NameChoice_Taylor:: @ 81C57A2
    .string "Taylor$"

gText_NameChoice_Oscar:: @ 81C57A9
    .string "Oscar$"

gText_NameChoice_Hiro:: @ 81C57AF
    .string "Hiro$"

gText_NameChoice_Max:: @ 81C57B4
    .string "Max$"

gText_NameChoice_Jon:: @ 81C57B8
    .string "Jon$"

gText_NameChoice_Ralph:: @ 81C57BC
    .string "Ralph$"

gText_NameChoice_Kay:: @ 81C57C2
    .string "Kay$"

gText_NameChoice_Tosh:: @ 81C57C6
    .string "Tosh$"

gText_NameChoice_Roak:: @ 81C57CB
    .string "Roak$"

gText_NameChoice_Omi:: @ 81C57D0
    .string "Omi$"

gText_NameChoice_Jodi:: @ 81C57D4
    .string "Jodi$"

gText_NameChoice_Amanda:: @ 81C57D9
    .string "Amanda$"

gText_NameChoice_Hillary:: @ 81C57E0
    .string "Hillary$"

gText_NameChoice_Makey:: @ 81C57E8
    .string "Makey$"

gText_NameChoice_Michi:: @ 81C57EE
    .string "Michi$"

gText_NameChoice_Paula:: @ 81C57F4
    .string "Paula$"

gText_NameChoice_June:: @ 81C57FA
    .string "June$"

gText_NameChoice_Cassie:: @ 81C57FF
    .string "Cassie$"

gText_NameChoice_Rey:: @ 81C5806
    .string "Rey$"

gText_NameChoice_Seda:: @ 81C580A
    .string "Seda$"

gText_NameChoice_Kiko:: @ 81C580F
    .string "Kiko$"

gText_NameChoice_Mina:: @ 81C5814
    .string "Mina$"

gText_NameChoice_Norie:: @ 81C5819
    .string "Norie$"

gText_NameChoice_Sai:: @ 81C581F
    .string "Sai$"

gText_NameChoice_Momo:: @ 81C5823
    .string "Momo$"

gText_NameChoice_Suzi:: @ 81C5828
    .string "Suzi$"

gText_NewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gText_NewGame_HelpDocs2:: @ 81C5875
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gText_NewGame_HelpDocs3:: @ 81C58BA
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gText_NewGame_HelpDocs4:: @ 81C58F9
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gText_NewGame_HelpDocs5:: @ 81C592B
    .string "Press this button to open the\n"
    .string "MENU.$"

gText_NewGame_HelpDocs6:: @ 81C594F
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gText_NewGame_HelpDocs7:: @ 81C5981
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gText_Oak_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gText_NewGame_AdventureIntro1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gText_NewGame_AdventureIntro2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gText_NewGame_AdventureIntro3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gText_Oak_WelcomeToTheWorld:: @ 81C5C78
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gText_Oak_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gText_Oak_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gText_Oak_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gText_Oak_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gText_Oak_AskPlayerName:: @ 81C5DEA
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gText_Oak_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gText_Oak_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gText_Oak_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gText_Oak_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gText_Oak_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gText_Oak_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pYour very own POKéMON legend is\n"
    .string "about to unfold!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"

gText_NewNameSpa:: @ 81C574F
    .string "Otro Nombre$"

gText_NameChoice_GreenSpa:: @ 81C5758
    .string "Verte$"

gText_NameChoice_RedSpa:: @ 81C575E
    .string "Joro$"

gText_NameChoice_LeafSpa:: @ 81C5762
    .string "Jaho$"

gText_NameChoice_FireSpa:: @ 81C5767
    .string "Guefo$"

gText_NameChoice_GarySpa:: @ 81C576C
    .string "Bosco$"

gText_NameChoice_KazSpa:: @ 81C5771
    .string "Floren$"

gText_NameChoice_ToruSpa:: @ 81C5775
    .string "Silvio$"

gText_NameChoice_AshSpa:: @ 81C577A
    .string "Furio$"

gText_NameChoice_KeneSpa:: @ 81C577E
    .string "Llamín$"

gText_NameChoice_GekiSpa:: @ 81C5783
    .string "Candel$"

gText_NameChoice_JakSpa:: @ 81C5788
    .string "Juno$"

gText_NameChoice_JanneSpa:: @ 81C578C
    .string "Juan$"

gText_NameChoice_JonnSpa:: @ 81C5792
    .string "Juanma$"

gText_NameChoice_KamonSpa:: @ 81C5797
    .string "Álvaro$"

gText_NameChoice_KarlSpa:: @ 81C579D
    .string "Ral$"

gText_NameChoice_TaylorSpa:: @ 81C57A2
    .string "Marino$"

gText_NameChoice_OscarSpa:: @ 81C57A9
    .string "Toilo$"

gText_NameChoice_HiroSpa:: @ 81C57AF
    .string "Ner$"

gText_NameChoice_MaxSpa:: @ 81C57B4
    .string "Max$"

gText_NameChoice_JonSpa:: @ 81C57B8
    .string "Morel$"

gText_NameChoice_RalphSpa:: @ 81C57BC
    .string "Rafa$"

gText_NameChoice_KaySpa:: @ 81C57C2
    .string "Ver$"

gText_NameChoice_ToshSpa:: @ 81C57C6
    .string "Lerio$"

gText_NameChoice_RoakSpa:: @ 81C57CB
    .string "Rodi$"

gText_NameChoice_OmiSpa:: @ 81C57D0
    .string "Mena$"

gText_NameChoice_JodiSpa:: @ 81C57D4
    .string "Cira$"

gText_NameChoice_AmandaSpa:: @ 81C57D9
    .string "María$"

gText_NameChoice_HillarySpa:: @ 81C57E0
    .string "Mina$"

gText_NameChoice_MakeySpa:: @ 81C57E8
    .string "Nena$"

gText_NameChoice_MichiSpa:: @ 81C57EE
    .string "Luna$"

gText_NameChoice_PaulaSpa:: @ 81C57F4
    .string "Bruna$"

gText_NameChoice_JuneSpa:: @ 81C57FA
    .string "Claudia$"

gText_NameChoice_CassieSpa:: @ 81C57FF
    .string "Casilda$"

gText_NameChoice_ReySpa:: @ 81C5806
    .string "Rita$"

gText_NameChoice_SedaSpa:: @ 81C580A
    .string "Selena$"

gText_NameChoice_KikoSpa:: @ 81C580F
    .string "Matilda$"

gText_NameChoice_MinaSpa:: @ 81C5814
    .string "Nuria$"

gText_NameChoice_NorieSpa:: @ 81C5819
    .string "Marina$"

gText_NameChoice_SaiSpa:: @ 81C581F
    .string "Salia$"

gText_NameChoice_MomoSpa:: @ 81C5823
    .string "Mirta$"

gText_NameChoice_SuziSpa:: @ 81C5828
    .string "Susa$"

gText_NewGame_HelpDocs1Spa:: @ 81C582D
    .string "La explicación de los botones\n"
    .string "se hará por orden de importancia.$"

gText_NewGame_HelpDocs2Spa:: @ 81C5875
    .string "Mover al protagonista de la\n"
    .string "historia. Seleccionar opciones.$"

gText_NewGame_HelpDocs3Spa:: @ 81C58BA
    .string "Confirmar opciones, curiosear\n"
    .string "cosas, chatear y leer texto.$"

gText_NewGame_HelpDocs4Spa:: @ 81C58F9
    .string "Retroceder, cancelar opciones\n"
    .string "y salir de distintos menús.$"

gText_NewGame_HelpDocs5Spa:: @ 81C592B
    .string "Abrir el menú.$"

gText_NewGame_HelpDocs6Spa:: @ 81C594F
    .string "Cambiar objetos de lugar y usar\n"
    .string "el que haya registrado.$"

gText_NewGame_HelpDocs7Spa:: @ 81C5981
    .string "Acceder al sistema de AYUDA.$"

gText_Oak_AskPlayerGenderSpa:: @ 81C59D5
    .string "Hola, ¿eres chico o chica?$"

gText_NewGame_AdventureIntro1Spa::
    .string "Estás a punto de sumergirte en un\n"
    .string "mundo lleno de aventuras de las\n"
    .string "que vas a ser protagonista.\n"
    .string "\n"
    .string "Habla con la gente y curiosea todo\n"
    .string "lo que te llame la atención, estés\n"
    .string "donde estés. Consigue información\n"
    .string "y pistas de todo lo que te rodee.$"

gText_NewGame_AdventureIntro2Spa::
    .string "Durante el largo camino, tendrás\n"
    .string "que ayudar a gente, enfrentarte\n"
    .string "a desafíos y resolver misterios.\n"
    .string "\n"
    .string "Te cruzarás con rivales y criaturas\n"
    .string "salvajes que querrán luchar\n"
    .string "contigo, pero ¡ánimo, tú puedes!$"

gText_NewGame_AdventureIntro3Spa::
    .string "Recuerda, habla con todo el mundo;\n"
    .string "crecerás como persona, y ése es\n"
    .string "tu principal objetivo.\n"
    .string "\n"
    .string "Pulsa el Botón A, ¡que comience\n"
    .string "la aventura!$"

gText_Oak_WelcomeToTheWorldSpa:: @ 81C5C78
    .string "¡Hola!\n"
    .string "¡Éste es el mundo de POKéMON!\p¡Me llamo OAK!\p¡Pero la gente me llama\n"
    .string "PROFESOR POKéMON!\p$"

gText_Oak_WorldInhabited1Spa:: @ 81C5D06
    .string "¡Este mundo está$"

gText_Oak_WorldInhabited2Spa:: @ 81C5D12
    .string "habitado por unas criaturas\n"
    .string "llamadas POKéMON!\p$"

gText_Oak_PetsBattlingStudySpa:: @ 81C5D4B
    .string "Para algunos, los POKéMON son\n"
    .string "mascotas. Pero otros los usan\n"
    .string "para pelear.\pEn cuanto a mí...\pEstudio a los POKéMON como\n"
    .string "profesión.\p$"

gText_Oak_TellMeALittleAboutYourselfSpa:: @ 81C5DBD
    .string "Bueno, cuéntame algo de ti.\p$"

gText_Oak_AskPlayerNameSpa:: @ 81C5DEA
    .string "Pero primero dime cómo te llamas.\p$"

gText_Oak_FinalizePlayerNameSpa:: @ 81C5E13
    .string "¡Bien!\n"
    .string "¡Así que te llamas {PLAYER}!$"

gText_Oak_IntroduceRivalSpa:: @ 81C5E2E
    .string "Éste es mi nieto.\pHa sido tu rival desde que erais\n"
    .string "pequeños.\pMmm... ¿podrías decirme cómo\n"
    .string "se llama?$"

gText_Oak_AskRivalNameSpa:: @ 81C5E91
    .string "¿Cómo era el nombre de tu rival?$"

gText_Oak_ConfirmRivalNameSpa:: @ 81C5EB5
    .string "Eh..., ¿era {RIVAL}?$"

gText_Oak_RememberRivalNameSpa:: @ 81C5EC5
    .string "¡Ah, sí! ¡Es verdad!\n"
    .string "¡Se llamaba {RIVAL}!\p$"

gText_Oak_LegendAboutToUnfoldSpa:: @ 81C5EF4
    .string "¡{PLAYER}!\p¡Tu propia leyenda POKéMON está\n"
    .string "a punto de comenzar!\p¡Te espera un mundo de sueños y\n"
    .string "aventuras con los POKéMON!\n"
    .string "¡Adelante!$"
