gText_NewName:: @ 81C574F
    .string "NEW NAME$"

gText_NameChoice_Green:: @ 81C5758
    .string "GREEN$"

gText_NameChoice_Red:: @ 81C575E
    .string "RED$"

gText_NameChoice_Leaf:: @ 81C5762
    .string "LEAF$"

gText_NameChoice_Fire:: @ 81C5767
    .string "FIRE$"

gText_NameChoice_Gary:: @ 81C576C
    .string "GARY$"

gText_NameChoice_Kaz:: @ 81C5771
    .string "KAZ$"

gText_NameChoice_Toru:: @ 81C5775
    .string "TORU$"

gText_NameChoice_Ash:: @ 81C577A
    .string "ASH$"

gText_NameChoice_Kene:: @ 81C577E
    .string "KENE$"

gText_NameChoice_Geki:: @ 81C5783
    .string "GEKI$"

gText_NameChoice_Jak:: @ 81C5788
    .string "JAK$"

gText_NameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gText_NameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gText_NameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gText_NameChoice_Karl:: @ 81C579D
    .string "KARL$"

gText_NameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gText_NameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gText_NameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gText_NameChoice_Max:: @ 81C57B4
    .string "MAX$"

gText_NameChoice_Jon:: @ 81C57B8
    .string "JON$"

gText_NameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gText_NameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gText_NameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gText_NameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gText_NameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gText_NameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gText_NameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gText_NameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gText_NameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gText_NameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gText_NameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gText_NameChoice_June:: @ 81C57FA
    .string "JUNE$"

gText_NameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gText_NameChoice_Rey:: @ 81C5806
    .string "REY$"

gText_NameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gText_NameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gText_NameChoice_Mina:: @ 81C5814
    .string "MINA$"

gText_NameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gText_NameChoice_Sai:: @ 81C581F
    .string "SAI$"

gText_NameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gText_NameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gText_NewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons will be explained in\n"
    .string "the order of their importance.$"

gText_NewGame_HelpDocs2:: @ 81C5875
    .string "Moves the main character.\n"
    .string "Also used to choose various data\n"
    .string "headings.$"

gText_NewGame_HelpDocs3:: @ 81C58BA
    .string "Used to confirm a choice, check\n"
    .string "things, chat, and scroll text.$"

gText_NewGame_HelpDocs4:: @ 81C58F9
    .string "Used to exit, cancel a choice,\n"
    .string "and cancel a mode.$"

gText_NewGame_HelpDocs5:: @ 81C592B
    .string "Press this button to open the\n"
    .string "MENU.$"

gText_NewGame_HelpDocs6:: @ 81C594F
    .string "Used to shift items and to use\n"
    .string "a registered item.$"

gText_NewGame_HelpDocs7:: @ 81C5981
    .string "If you need help playing the\n"
    .string "game, or on how to do things,\n"
    .string "press the L or R Button.$"

gText_Oak_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gText_NewGame_AdventureIntro1::
    .string "In the world which you are about to\n"
    .string "enter, you will embark on a grand\n"
    .string "adventure with you as the hero.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gText_NewGame_AdventureIntro2::
    .string "New paths will open to you by helping\n"
    .string "people in need, overcoming challenges,\n"
    .string "and solving mysteries.\n"
    .string "\n"
    .string "At times, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Be brave and keep pushing on.$"

gText_NewGame_AdventureIntro3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of people and achieve personal growth.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "adventure begin!$"

gText_Oak_WelcomeToTheWorld:: @ 81C5C78
    .string "Hello, there!\n"
    .string "Glad to meet you!\pWelcome to the world of POKéMON!\pMy name is OAK.\pPeople affectionately refer to me\n"
    .string "as the POKéMON PROFESSOR.\p$"

gText_Oak_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gText_Oak_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gText_Oak_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI study POKéMON as a profession.\p$"

gText_Oak_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "But first, tell me a little about\n"
    .string "yourself.\p$"

gText_Oak_AskPlayerName:: @ 81C5DEA
    .string "Let's begin with your name.\n"
    .string "What is it?\p$"

gText_Oak_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gText_Oak_IntroduceRival:: @ 81C5E2E
    .string "This is my grandson.\pHe's been your rival since you both\n"
    .string "were babies.\p…Erm, what was his name now?$"

gText_Oak_AskRivalName:: @ 81C5E91
    .string "Your rival's name, what was it now?$"

gText_Oak_ConfirmRivalName:: @ 81C5EB5
    .string "…Er, was it {RIVAL}?$"

gText_Oak_RememberRivalName:: @ 81C5EC5
    .string "That's right! I remember now!\n"
    .string "His name is {RIVAL}!\p$"

gText_Oak_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pYour very own POKéMON legend is\n"
    .string "about to unfold!\pA world of dreams and adventures\n"
    .string "with POKéMON awaits! Let's go!$"
