gText_BootedUpPC:: @ 81A5075
	.string "{PLAYER} booted up the PC.$"

gText_AccessWhichPC:: @ 81A508A
	.string "Which PC should be accessed?$"

gText_AccessedSomeonesPC:: @ 81A50A7
	.string "Accessed Someone's PC.$"

gText_OpenedPkmnStorage:: @ 81A50BE
	.string "Pokémon Storage System opened.$"

gText_AccessedPlayersPC:: @ 81A50DD
	.string "Accessed {PLAYER}'s PC.$"

gText_AccessedBillsPC:: @ 81A50EF
	.string "Accessed Bill's PC.$"

gText_BootedUpPCSpa:: @ 81A5075
	.string "{PLAYER} encendió el PC.$"

gText_AccessWhichPCSpa:: @ 81A508A
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPCSpa:: @ 81A50A7
	.string "Accedió al PC de alguien.$"

gText_OpenedPkmnStorageSpa:: @ 81A50BE
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de Pokémon\l"
	.string "concedido.$"

gText_AccessedPlayersPCSpa:: @ 81A50DD
	.string "Accedió al PC de {PLAYER}.$"

gText_AccessedBillsPCSpa:: @ 81A50EF
	.string "Accedió al PC de Bill.$"
