gText_MonSentToBoxInSomeonesPC:: @ 81A5CF1
    .string "{STR_VAR_2} was transferred to\n"
    .string "Someone's PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

gText_MonSentToBoxInBillsPC:: @ 81A5D31
    .string "{STR_VAR_2} was transferred to\n"
    .string "BILL'S PC.\p"
    .string "It was placed in \n"
    .string "BOX “{STR_VAR_1}.”$"

gText_MonSentToBoxSomeonesBoxFull:: @ 81A5D6E
    .string "BOX “{STR_VAR_3}” on\n"
    .string "Someone's PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

gText_MonSentToBoxBillsBoxFull:: @ 81A5DB1
    .string "BOX “{STR_VAR_3}” on\n"
    .string "BILL'S PC was full.\p"
    .string "{STR_VAR_2} was transferred to\n"
    .string "BOX “{STR_VAR_1}.”$"

Text_PlayerObtainedTheMon:: @ 81A5DF1
    .string "{PLAYER} obtained\n"
    .string "the {STR_VAR_1}!$"

Text_NoMoreRoomForPokemon:: @ 81A5E31
    .string "There's no more room for POKéMON!\p"
    .string "The POKéMON BOXES are full and\n"
    .string "can't accept any more!$"

gText_MonSentToBoxInSomeonesPCSpa:: @ 81A5CF1
    .string "{STR_VAR_2} fue enviado al PC\n"
    .string "de alguien.\p"
    .string "Se ha guardado en la CAJA\n"
    .string "“{STR_VAR_1}”.$"

gText_MonSentToBoxInBillsPCSpa:: @ 81A5D31
    .string "{STR_VAR_2} fue enviado al PC\n"
    .string "de BILL.\p"
    .string "Se ha guardado en la CAJA\n"
    .string "“{STR_VAR_1}”.$"

gText_MonSentToBoxSomeonesBoxFullSpa:: @ 81A5D6E
    .string "La CAJA “{STR_VAR_3}” del PC\n"
    .string "de alguien estaba llena.\p"
    .string "{STR_VAR_2} fue enviado a la CAJA\n"
    .string "“{STR_VAR_1}”.$"

gText_MonSentToBoxBillsBoxFullSpa:: @ 81A5DB1
    .string "La CAJA “{STR_VAR_3}” del PC\n"
    .string "de BILL estaba llena.\p"
    .string "{STR_VAR_2} fue enviado a la CAJA\n"
    .string "“{STR_VAR_1}”.$"

Text_PlayerObtainedTheMonSpa:: @ 81A5DF1
    .string "{PLAYER} obtuvo\n"
    .string "el {STR_VAR_1}!$"

Text_NoMoreRoomForPokemonSpa:: @ 81A5E31
    .string "¡No queda sitio para más POKéMON!\p"
    .string "¡Las CAJAS POKéMON están llenas!$"
