gText_MayIHelpYou:: @ 81A6211
	.string "Hi, there!\n"
	.string "May I help you?$"

gText_FillOutQuestionnaire:: @ 81A622C
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

gText_QuestionnaireThankYou:: @ 81A6265
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

gText_YouKnowThoseWords:: @ 81A62D3
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"

gText_YouCanAccessMysteryGift:: @ 81A6359
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"

gText_ThankYouForAccessingMysteryGift:: @ 81A6393
	.string "Thank you for accessing the\n"
	.string "MYSTERY GIFT System.$"
	
//SPANISH

gText_MayIHelpYouSpa:: @ 81A6211
	.string "¡Hola! ¿Puedo ayudarte en algo?$"

gText_FillOutQuestionnaireSpa:: @ 81A622C
	.string "Hay un cuestionario.\n"
	.string "¿Quieres rellenarlo?$"

gText_QuestionnaireThankYouSpa:: @ 81A6265
	.string "Gracias por rellenar el\n"
	.string "cuestionario. Usaremos tus\l"
	.string "respuestas a modo de referencia.$"

gText_YouKnowThoseWordsSpa:: @ 81A62D3
	.string "Hola, ¿conoces las palabras?\p"
	.string "Pues entonces debes de saber\n"
	.string "de qué va el REGALO MISTERIOSO.\p"
	.string "¡A partir de ahora, podrás recibir\n"
	.string "REGALOS MISTERIOSOS!$"

gText_YouCanAccessMysteryGiftSpa:: @ 81A6359
	.string "Una vez guardes la partida, podrás\n"
	.string "acceder al REGALO MISTERIOSO.$"

gText_ThankYouForAccessingMysteryGiftSpa:: @ 81A6393
	.string "Gracias por acceder al sistema\n"
	.string "del REGALO MISTERIOSO."
