PokedexRating_Text_HowIsPokedexComingAlong:: @ 81A6C51
	.string "OAK: Good to see you!\n"
	.string "How is your POKéDEX coming along?\p"
	.string "Here, let me take a look.$"

PokedexRating_Text_SeenXOwnedY:: @ 81A6CA3
	.string "The amount of progress you've made\n"
	.string "on your POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.\p"
	.string "{SIZE}ÁPROF. OAK's rating:$"

PokedexRating_Text_LessThan10:: @ 81A6D17
	.string "You still have lots to do.\p"
	.string "Go into every patch of grass you\n"
	.string "see and look for POKéMON!$"

PokedexRating_Text_LessThan20:: @ 81A6D6D
	.string "It looks as if you're getting on\n"
	.string "the right track!\p"
	.string "I've given one of my AIDES a FLASH\n"
	.string "HM. Make sure you go get it!$"

PokedexRating_Text_LessThan30:: @ 81A6DDF
	.string "Your POKéDEX could use a bit more\n"
	.string "volume still!\p"
	.string "Try to catch other species of\n"
	.string "POKéMON!$"

PokedexRating_Text_LessThan40:: @ 81A6E36
	.string "Good, it's apparent that you're\n"
	.string "trying hard!\p"
	.string "I've given one of my AIDES an\n"
	.string "ITEMFINDER. Be sure to collect it!$"

PokedexRating_Text_LessThan50:: @ 81A6EA4
	.string "Your POKéDEX is coming along quite\n"
	.string "well!\p"
	.string "I've given one of my AIDES an\n"
	.string "AMULET COIN. Be sure to get it!$"

PokedexRating_Text_LessThan60:: @ 81A6F0B
	.string "Ah, you've finally topped 50\n"
	.string "species!\p"
	.string "I've given one of my AIDES an EXP.\n"
	.string "SHARE. Be sure to go get it!$"

PokedexRating_Text_LessThan70:: @ 81A6F71
	.string "Hoho! This is turning into quite the\n"
	.string "respectable POKéDEX!$"

PokedexRating_Text_LessThan80:: @ 81A6FAB
	.string "Very good!\p"
	.string "I think you'll collect even more\n"
	.string "POKéMON by going fishing!$"

PokedexRating_Text_LessThan90:: @ 81A6FF1
	.string "Wonderful! Let me guess… You\n"
	.string "like to collect things, don't you?$"

PokedexRating_Text_LessThan100:: @ 81A7031
	.string "I'm impressed!\n"
	.string "It must have been difficult to do!$"

PokedexRating_Text_LessThan110:: @ 81A7063
	.string "You've finally hit 100 species!\n"
	.string "I can't believe how good you are!$"

PokedexRating_Text_LessThan120:: @ 81A70A5
	.string "You even have the evolved forms\n"
	.string "of POKéMON! Super!$"

PokedexRating_Text_LessThan130:: @ 81A70D8
	.string "Excellent! Trade with friends to\n"
	.string "get some more!$"

PokedexRating_Text_LessThan140:: @ 81A7108
	.string "Outstanding!\n"
	.string "You've become a real pro at this!$"

PokedexRating_Text_LessThan150:: @ 81A7137
	.string "I have nothing left to say!\n"
	.string "You're the POKéMON PROFESSOR now!$"

PokedexRating_Text_Complete:: @ 81A7175
	.string "Your POKéDEX is entirely complete!\n"
	.string "Congratulations!!$"

PokedexRating_Text_NationalDexSeenXOwnedY:: @ 81A71AA
	.string "And your NATIONAL POKéDEX is:\p"
	.string "{STR_VAR_1} POKéMON seen and\n"
	.string "{STR_VAR_2} POKéMON owned.$"

PokedexRating_Text_LookForwardToFilledNationalDex:: @ 81A71EE
	.string "I'll be looking forward to seeing\n"
	.string "you fill the NATIONAL POKéDEX!$"

PokedexRating_Text_YouveCompletedDex:: @ 81A722F
	.string "Finally…\p"
	.string "You've finally completed the\n"
	.string "POKéDEX!\p"
	.string "It's magnificent!\n"
	.string "Truly, this is a fantastic feat!$"

PokedexRating_Text_Wroooaaarrr:: @ 81A7291
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_HaHa:: @ 81A72A6
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamReality:: @ 81A72AD
	.string "Thank you, {PLAYER}!\n"
	.string "Sincerely, thank you!\l"
	.string "You've made my dream a reality!$"

PokedexRating_Text_LoveSeeingYourPokedex:: @ 81A72F2
	.string "OAK: Ah, welcome!\p"
	.string "Tell me, how is your POKéDEX\n"
	.string "coming along?\p"
	.string "Wahaha!\p"
	.string "Actually, I know how it is, but I\n"
	.string "love seeing it anyway!\p"
	.string "Let's see…$"








PokedexRating_Text_HowIsPokedexComingAlongSpa:: @ 81A6C51
	.string "OAK: ¡Encantado de verte!\n"
	.string "¿Cómo va tu POKéDEX?\p"
	.string "¡Déjame que le eche un vistazo!$"

PokedexRating_Text_SeenXOwnedYSpa:: @ 81A6CA3
	.string "Nivel POKéDEX:n"
	.string "Has visto {STR_VAR_1} POKéMON\n"
	.string "Tienes {STR_VAR_2} POKéMON\p"
	.string "Evaluación del PROF. OAK:$"

PokedexRating_Text_LessThan10Spa:: @ 81A6D17
	.string "Te queda mucho por hacer.\p"
	.string "¡Busca a los POKéMON en las zonas\n"
	.string "de hierba!$"

PokedexRating_Text_LessThan20Spa:: @ 81A6D6D
	.string "¡Estás en buen camino!\n"
	.string "¡Pídele a uno de mis AYUDANTES\p"
	.string "la MO DESTELLO que le\n"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan30Spa:: @ 81A6DDF
	.string "¡Necesitas más POKéMON!\n"
	.string "¡Intenta capturar otras especies!$"

PokedexRating_Text_LessThan40Spa:: @ 81A6E36
	.string "¡Muy bien!\n"
	.string "¡Pídele a uno de mis AYUDANTES\p"
	.string "un BUSCAOBJETOS que le\n"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan50Spa:: @ 81A6EA4
	.string "¡Tu POKéDEX va de maravilla!\n"
	.string "¡Pídele a uno de mis AYUDANTES\p"
	.string "la MONEDA AMULETO que le\n"
	.string "he dado para ti!$"

PokedexRating_Text_LessThan60Spa:: @ 81A6F0B
	.string "¡Ya has conseguido 50 especies!\n"
	.string "¡Pídele a uno de mis AYUDANTES\p"
	.string "el REPARTIR EXP. que le he dado\n"
	.string "para ti!$"

PokedexRating_Text_LessThan70Spa:: @ 81A6F71
	.string "¡Oh!n"
	.string "¡Lo estás haciendo genial!$"

PokedexRating_Text_LessThan80Spa:: @ 81A6FAB
	.string "¡Excelente!\p"
	.string "¡Ve a pescar algunos POKéMON\n"
	.string "del mar!$"

PokedexRating_Text_LessThan90Spa:: @ 81A6FF1
	.string "¡Magnífico!\n"
	.string "Te encanta coleccionar cosas, ¿eh?$"

PokedexRating_Text_LessThan100Spa:: @ 81A7031
	.string "¡Impresionante!\n"
	.string "¡Debe de haber sido muy difícil!$"

PokedexRating_Text_LessThan110Spa:: @ 81A7063
	.string "¡Por fin tienes 100 especies!\n"
	.string "¡Se te da genial!$"

PokedexRating_Text_LessThan120Spa:: @ 81A70A5
	.string "¡Y has conseguido hasta transformar\n"
	.string "a tus POKéMON! ¡Eres genial!$"

PokedexRating_Text_LessThan130Spa:: @ 81A70D8
	.string "¡Excelente! ¡Intercambia con tus\n"
	.string "amigos y tendrás más!$"

PokedexRating_Text_LessThan140Spa:: @ 81A7108
	.string "¡Impresionante!\n"
	.string "¡Eres muy profesional!$"

PokedexRating_Text_LessThan150Spa:: @ 81A7137
	.string "¡No tengo nada más que decir!\n"
	.string "¡Ahora eres una eminencia!$"

PokedexRating_Text_CompleteSpa:: @ 81A7175
	.string "¡Tu POKéDEX está completa!\n"
	.string "¡Enhorabuena!$"

PokedexRating_Text_NationalDexSeenXOwnedYSpa:: @ 81A71AA
	.string "A ver cómo llevas la POKéDEX\n"
	.string "NACIONAL:\p"
	.string "POKéMON avistados: {STR_VAR_1}\n"
	.string "POKéMON atrapados: {STR_VAR_2}$"

PokedexRating_Text_LookForwardToFilledNationalDexSpa:: @ 81A71EE
	.string "¡Estoy deseando ver cómo completas\n"
	.string "la POKéDEX NACIONAL!$"

PokedexRating_Text_YouveCompletedDexSpa:: @ 81A722F
	.string "¡Por fin!\n"
	.string "¡Ya has completado la POKéDEX!\p"
	.string "¡Magnífico!\n"
	.string "¡De verdad, no era tarea fácil!$"

PokedexRating_Text_WroooaaarrrSpa:: @ 81A7291
	.string "¡Guuuaaaaauuuuu!$"

PokedexRating_Text_HaHaSpa:: @ 81A72A6
	.string "はあ はあ‥$"

PokedexRating_Text_ThankYouMadeDreamRealitySpa:: @ 81A72AD
	.string "¡Gracias, {PLAYER}!\n"
	.string "Gracias de verdad.\l"
	.string "¡Has hecho mi sueño realidad!$"

PokedexRating_Text_LoveSeeingYourPokedexSpa:: @ 81A72F2
	.string "OAK: ¡Hola!\p"
	.string "¿Qué tal llevas la POKéDEX?\n"
	.string "A ver...\p"
	.string "La verdad es que sé cómo es, pero\n"
	.string "me gusta verla de todas formas.\p"
	.string "A ver, a ver...$"
