gText_WouldYouLikeToSaveTheGame:: @ 81C55C9
	.string "Would you like to save the game?$"

gText_AlreadySaveFile_WouldLikeToOverwrite:: @ 81C55EA
	.string "There is already a saved file.\n"
	.string "Is it okay to overwrite it?$"

gText_SavingDontTurnOffThePower:: @ 81C5625
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedTheGame:: @ 81C5647
	.string "{PLAYER} saved the game.$"

gText_SaveFailed::
	.string "セーブに　しっぱい　しました‥$"

gText_DifferentGameFile:: @ 81C566A
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_WouldYouLikeToSaveTheGameSpa:: @ 81C55C9
	.string "¿Quieres guardar la partida?$"

gText_AlreadySaveFile_WouldLikeToOverwriteSpa:: @ 81C55EA
	.string "Ya hay una partida guardada.\n"
	.string "¿Quieres sobrescribirla?$"

gText_SavingDontTurnOffThePowerSpa:: @ 81C5625
	.string "Guardando...\n"
	.string "No Apagues la Consola.$"

gText_PlayerSavedTheGameSpa:: @ 81C5647
	.string "{PLAYER} guardó la partida.$"

gText_DifferentGameFileSpa:: @ 81C566A
	.string "¡ATENCIÓN!\p"
	.string "Ya hay una partida guardada.\p"
	.string "Si guardas, perderás los datos\n"
	.string "de la partida incluyendo los\l"
	.string "objetos y los Pokémon.\p"
	.string "¿Seguro que quieres guardar ahora\n"
	.string "y sobrescribir los otros datos?$"
